<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Data transformation | Python for Data Science</title>
  <meta name="description" content="This book will teach you how to do data science with R Python: You’ll learn how to get your data into Python, get it into the most useful structure, transform it, visualise it and model it. In this book, you will find a practicum of skills for data science. Just as a chemist learns how to clean test tubes and stock a lab, you’ll learn how to clean data and draw plots—and many other things besides. These are the skills that allow data science to happen, and here you will find the best practices for doing each of these things with Python. You’ll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You’ll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualising, and exploring data." />
  <meta name="generator" content="bookdown 0.19.1 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Data transformation | Python for Data Science" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://byuidatascience.github.io/python4ds/" />
  <meta property="og:image" content="https://byuidatascience.github.io/python4ds/cover.png" />
  <meta property="og:description" content="This book will teach you how to do data science with R Python: You’ll learn how to get your data into Python, get it into the most useful structure, transform it, visualise it and model it. In this book, you will find a practicum of skills for data science. Just as a chemist learns how to clean test tubes and stock a lab, you’ll learn how to clean data and draw plots—and many other things besides. These are the skills that allow data science to happen, and here you will find the best practices for doing each of these things with Python. You’ll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You’ll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualising, and exploring data." />
  <meta name="github-repo" content="byuidatascience/python4ds" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Data transformation | Python for Data Science" />
  <meta name="twitter:site" content="@byuidss" />
  <meta name="twitter:description" content="This book will teach you how to do data science with R Python: You’ll learn how to get your data into Python, get it into the most useful structure, transform it, visualise it and model it. In this book, you will find a practicum of skills for data science. Just as a chemist learns how to clean test tubes and stock a lab, you’ll learn how to clean data and draw plots—and many other things besides. These are the skills that allow data science to happen, and here you will find the best practices for doing each of these things with Python. You’ll learn how to use the grammar of graphics, literate programming, and reproducible research to save time. You’ll also learn how to manage cognitive resources to facilitate discoveries when wrangling, visualising, and exploring data." />
  <meta name="twitter:image" content="https://byuidatascience.github.io/python4ds/cover.png" />

<meta name="author" content="J. Hathaway" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="workflow-basics.html"/>
<link rel="next" href="workflow-scripts.html"/>
<script src="libs/header-attrs-2.1.4/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/vega-5.9.0/vega.min.js"></script>
<script src="libs/vega-lite-4.0.2/vega-lite.min.js"></script>
<link href="libs/vega-embed-6.2.0/vega-embed.css" rel="stylesheet" />
<script src="libs/vega-embed-6.2.0/vega-embed.js"></script>
<script src="libs/vegawidget-binding-0.3.1.9003/vegawidget.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115082821-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-115082821-1');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="r4ds.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">Python for Data Science</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-you-will-learn"><i class="fa fa-check"></i><b>1.1</b> What you will learn</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#how-this-book-is-organised"><i class="fa fa-check"></i><b>1.2</b> How this book is organised</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#what-you-wont-learn"><i class="fa fa-check"></i><b>1.3</b> What you won’t learn</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#big-data"><i class="fa fa-check"></i><b>1.3.1</b> Big data</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#r-julia-and-friends"><i class="fa fa-check"></i><b>1.3.2</b> R, Julia, and friends</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#non-rectangular-data"><i class="fa fa-check"></i><b>1.3.3</b> Non-rectangular data</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction.html"><a href="introduction.html#hypothesis-confirmation"><i class="fa fa-check"></i><b>1.3.4</b> Hypothesis confirmation</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#prerequisites"><i class="fa fa-check"></i><b>1.4</b> Prerequisites</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction.html"><a href="introduction.html#python"><i class="fa fa-check"></i><b>1.4.1</b> Python</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction.html"><a href="introduction.html#visual-studio-code-vs-code"><i class="fa fa-check"></i><b>1.4.2</b> Visual Studio Code (VS Code)</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction.html"><a href="introduction.html#package-management-pip"><i class="fa fa-check"></i><b>1.4.3</b> Package Management (pip)</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction.html"><a href="introduction.html#the-data-science-packages"><i class="fa fa-check"></i><b>1.4.4</b> The Data Science Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#running-python-code"><i class="fa fa-check"></i><b>1.5</b> Running Python code</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#getting-help-and-learning-more"><i class="fa fa-check"></i><b>1.6</b> Getting help and learning more</a></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#datasets-access"><i class="fa fa-check"></i><b>1.7</b> Datasets access</a></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i><b>1.8</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#colophon"><i class="fa fa-check"></i><b>1.9</b> Colophon</a></li>
</ul></li>
<li class="part"><span><b>I Explore</b></span></li>
<li class="chapter" data-level="2" data-path="explore-intro.html"><a href="explore-intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="data-visualisation.html"><a href="data-visualisation.html"><i class="fa fa-check"></i><b>3</b> Data visualisation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation.html"><a href="data-visualisation.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-visualisation.html"><a href="data-visualisation.html#prerequisites-1"><i class="fa fa-check"></i><b>3.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-visualisation.html"><a href="data-visualisation.html#altair-data-management"><i class="fa fa-check"></i><b>3.1.2</b> Altair data management</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation.html"><a href="data-visualisation.html#first-steps"><i class="fa fa-check"></i><b>3.2</b> First steps</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-visualisation.html"><a href="data-visualisation.html#the-mpg-data-frame"><i class="fa fa-check"></i><b>3.2.1</b> The <code>mpg</code> data frame</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-visualisation.html"><a href="data-visualisation.html#creating-an-altair-plot"><i class="fa fa-check"></i><b>3.2.2</b> Creating an Altair plot</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-visualisation.html"><a href="data-visualisation.html#a-graphing-template"><i class="fa fa-check"></i><b>3.2.3</b> A graphing template</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-visualisation.html"><a href="data-visualisation.html#exercises"><i class="fa fa-check"></i><b>3.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation.html"><a href="data-visualisation.html#aesthetic-mappings"><i class="fa fa-check"></i><b>3.3</b> Aesthetic mappings</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualisation.html"><a href="data-visualisation.html#exercises-1"><i class="fa fa-check"></i><b>3.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation.html"><a href="data-visualisation.html#common-problems"><i class="fa fa-check"></i><b>3.4</b> Common problems</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation.html"><a href="data-visualisation.html#facets"><i class="fa fa-check"></i><b>3.5</b> Facets</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="data-visualisation.html"><a href="data-visualisation.html#exercises-2"><i class="fa fa-check"></i><b>3.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation.html"><a href="data-visualisation.html#geometric-objects"><i class="fa fa-check"></i><b>3.6</b> Geometric objects</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="data-visualisation.html"><a href="data-visualisation.html#exercises-3"><i class="fa fa-check"></i><b>3.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation.html"><a href="data-visualisation.html#statistical-transformations"><i class="fa fa-check"></i><b>3.7</b> Statistical transformations</a></li>
<li class="chapter" data-level="3.8" data-path="data-visualisation.html"><a href="data-visualisation.html#position-adjustments"><i class="fa fa-check"></i><b>3.8</b> Position adjustments</a></li>
<li class="chapter" data-level="3.9" data-path="data-visualisation.html"><a href="data-visualisation.html#coordinate-systems-maps"><i class="fa fa-check"></i><b>3.9</b> Coordinate systems (maps)</a></li>
<li class="chapter" data-level="3.10" data-path="data-visualisation.html"><a href="data-visualisation.html#the-layered-grammar-of-graphics"><i class="fa fa-check"></i><b>3.10</b> The layered grammar of graphics</a></li>
<li class="chapter" data-level="3.11" data-path="data-visualisation.html"><a href="data-visualisation.html#altairs-grammar-of-graphics"><i class="fa fa-check"></i><b>3.11</b> Altair’s grammar of graphics</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="workflow-basics.html"><a href="workflow-basics.html"><i class="fa fa-check"></i><b>4</b> Workflow: basics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="workflow-basics.html"><a href="workflow-basics.html#coding-basics"><i class="fa fa-check"></i><b>4.1</b> Coding basics</a></li>
<li class="chapter" data-level="4.2" data-path="workflow-basics.html"><a href="workflow-basics.html#whats-in-a-name"><i class="fa fa-check"></i><b>4.2</b> What’s in a name?</a></li>
<li class="chapter" data-level="4.3" data-path="workflow-basics.html"><a href="workflow-basics.html#calling-functions"><i class="fa fa-check"></i><b>4.3</b> Calling functions</a></li>
<li class="chapter" data-level="4.4" data-path="workflow-basics.html"><a href="workflow-basics.html#exercises-4"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="transform.html"><a href="transform.html"><i class="fa fa-check"></i><b>5</b> Data transformation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="transform.html"><a href="transform.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="transform.html"><a href="transform.html#prerequisites-2"><i class="fa fa-check"></i><b>5.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="5.1.2" data-path="transform.html"><a href="transform.html#nycflights13"><i class="fa fa-check"></i><b>5.1.2</b> nycflights13</a></li>
<li class="chapter" data-level="5.1.3" data-path="transform.html"><a href="transform.html#pandas-data-manipulation-basics"><i class="fa fa-check"></i><b>5.1.3</b> pandas data manipulation basics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="transform.html"><a href="transform.html#filter-rows-with-query"><i class="fa fa-check"></i><b>5.2</b> Filter rows with <code>query()</code></a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="transform.html"><a href="transform.html#comparisons"><i class="fa fa-check"></i><b>5.2.1</b> Comparisons</a></li>
<li class="chapter" data-level="5.2.2" data-path="transform.html"><a href="transform.html#logical-operators"><i class="fa fa-check"></i><b>5.2.2</b> Logical operators</a></li>
<li class="chapter" data-level="5.2.3" data-path="transform.html"><a href="transform.html#missing-values"><i class="fa fa-check"></i><b>5.2.3</b> Missing values</a></li>
<li class="chapter" data-level="5.2.4" data-path="transform.html"><a href="transform.html#exercises-5"><i class="fa fa-check"></i><b>5.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="transform.html"><a href="transform.html#arrange-or-sort-rows-with-sort_values"><i class="fa fa-check"></i><b>5.3</b> Arrange or sort rows with <code>sort_values()</code></a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="transform.html"><a href="transform.html#exercises-6"><i class="fa fa-check"></i><b>5.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="transform.html"><a href="transform.html#select"><i class="fa fa-check"></i><b>5.4</b> Select columns with <code>filter()</code> or <code>loc[]</code></a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="transform.html"><a href="transform.html#exercises-7"><i class="fa fa-check"></i><b>5.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="transform.html"><a href="transform.html#add-new-variables-with-assign"><i class="fa fa-check"></i><b>5.5</b> Add new variables with <code>assign()</code></a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="transform.html"><a href="transform.html#mutate-funs"><i class="fa fa-check"></i><b>5.5.1</b> Useful creation functions</a></li>
<li class="chapter" data-level="5.5.2" data-path="transform.html"><a href="transform.html#exercises-8"><i class="fa fa-check"></i><b>5.5.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="transform.html"><a href="transform.html#grouped-summaries-or-aggregations-with-agg"><i class="fa fa-check"></i><b>5.6</b> Grouped summaries or aggregations with <code>agg()</code></a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="transform.html"><a href="transform.html#combining-multiple-operations-with-the-pipe"><i class="fa fa-check"></i><b>5.6.1</b> Combining multiple operations with the pipe</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="workflow-scripts.html"><a href="workflow-scripts.html"><i class="fa fa-check"></i><b>6</b> Workflow: scripts</a>
<ul>
<li class="chapter" data-level="6.1" data-path="workflow-scripts.html"><a href="workflow-scripts.html#running-code"><i class="fa fa-check"></i><b>6.1</b> Running code</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="workflow-projects.html"><a href="workflow-projects.html"><i class="fa fa-check"></i><b>7</b> Workflow: projects</a>
<ul>
<li class="chapter" data-level="7.1" data-path="workflow-projects.html"><a href="workflow-projects.html#what-is-real"><i class="fa fa-check"></i><b>7.1</b> What is real?</a></li>
<li class="chapter" data-level="7.2" data-path="workflow-projects.html"><a href="workflow-projects.html#where-does-your-analysis-live"><i class="fa fa-check"></i><b>7.2</b> Where does your analysis live?</a></li>
<li class="chapter" data-level="7.3" data-path="workflow-projects.html"><a href="workflow-projects.html#paths-and-directories"><i class="fa fa-check"></i><b>7.3</b> Paths and directories</a></li>
<li class="chapter" data-level="7.4" data-path="workflow-projects.html"><a href="workflow-projects.html#vs-code-workspaces"><i class="fa fa-check"></i><b>7.4</b> VS Code workspaces</a></li>
<li class="chapter" data-level="7.5" data-path="workflow-projects.html"><a href="workflow-projects.html#summary"><i class="fa fa-check"></i><b>7.5</b> Summary</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Python for Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="transform" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Data transformation</h1>
<div id="introduction-2" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>Visualization is an important tool for insight generation, but it is rare that you get the data in exactly the right form you need. Often you’ll need to create some new variables or summaries, or maybe you just want to rename the variables or reorder the observations in order to make the data a little easier to work with. You’ll learn how to do all that (and more!) in this chapter, which will teach you how to transform your data using the pandas package and a new dataset on flights departing New York City in 2013.</p>
<div id="prerequisites-2" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Prerequisites</h3>
<p>In this chapter we’re going to focus on how to use the pandas package, the foundational package for data science in Python. We’ll illustrate the key ideas using data from the nycflights13 R package, and use Altair to help us understand the data. We will also need the math package that comes with Python.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb60-1"><a href="transform.html#cb60-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb60-2"><a href="transform.html#cb60-2"></a><span class="im">import</span> altair <span class="im">as</span> alt</span>
<span id="cb60-3"><a href="transform.html#cb60-3"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb60-4"><a href="transform.html#cb60-4"></a></span>
<span id="cb60-5"><a href="transform.html#cb60-5"></a></span>
<span id="cb60-6"><a href="transform.html#cb60-6"></a>flights_url <span class="op">=</span> <span class="st">&quot;https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/flights/flights.csv&quot;</span></span>
<span id="cb60-7"><a href="transform.html#cb60-7"></a></span>
<span id="cb60-8"><a href="transform.html#cb60-8"></a>flights <span class="op">=</span> pd.read_csv(flights_url)</span>
<span id="cb60-9"><a href="transform.html#cb60-9"></a>flights[<span class="st">&#39;time_hour&#39;</span>] <span class="op">=</span> pd.to_datetime(flights.time_hour, <span class="bu">format</span> <span class="op">=</span> <span class="st">&quot;%Y-%m-</span><span class="sc">%d</span><span class="st"> %H:%M:%S&quot;</span>)</span></code></pre></div>
</div>
<div id="nycflights13" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> nycflights13</h3>
<p>To explore the basic data manipulation verbs of pandas, we’ll use <code>flights</code>. This data frame contains all 336,776 flights that departed from New York City in 2013. The data comes from the US <a href="http://www.transtats.bts.gov/DatabaseInfo.asp?DB_ID=120&amp;Link=0">Bureau of Transportation Statistics</a>, and is <a href="https://github.com/byuidatascience/data4python4ds/blob/master/data.md">documented here</a>.</p>
<pre><code>#&gt;         year  month  day  ...  hour  minute                 time_hour
#&gt; 0       2013      1    1  ...     5      15 2013-01-01 10:00:00+00:00
#&gt; 1       2013      1    1  ...     5      29 2013-01-01 10:00:00+00:00
#&gt; 2       2013      1    1  ...     5      40 2013-01-01 10:00:00+00:00
#&gt; 3       2013      1    1  ...     5      45 2013-01-01 10:00:00+00:00
#&gt; 4       2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00
#&gt; ...      ...    ...  ...  ...   ...     ...                       ...
#&gt; 336771  2013      9   30  ...    14      55 2013-09-30 18:00:00+00:00
#&gt; 336772  2013      9   30  ...    22       0 2013-10-01 02:00:00+00:00
#&gt; 336773  2013      9   30  ...    12      10 2013-09-30 16:00:00+00:00
#&gt; 336774  2013      9   30  ...    11      59 2013-09-30 15:00:00+00:00
#&gt; 336775  2013      9   30  ...     8      40 2013-09-30 12:00:00+00:00
#&gt; 
#&gt; [336776 rows x 19 columns]</code></pre>
<p>You might notice that this data frame does not print in its entirety as other data frames you might have seen in the past: it only shows the first few and last few rows with only the columns that fit on one screen. (To see the whole dataset, you can open the variable view in your interactive Python window and double click on the flights object which will open the dataset in the VS Code data viewer).</p>
<p>Using <code>flights.dtypes</code> will show you the variables types for each column. These describe the type of each variable:</p>
<pre><code>#&gt; year                            int64
#&gt; month                           int64
#&gt; day                             int64
#&gt; dep_time                      float64
#&gt; sched_dep_time                  int64
#&gt; dep_delay                     float64
#&gt; arr_time                      float64
#&gt; sched_arr_time                  int64
#&gt; arr_delay                     float64
#&gt; carrier                        object
#&gt; flight                          int64
#&gt; tailnum                        object
#&gt; origin                         object
#&gt; dest                           object
#&gt; air_time                      float64
#&gt; distance                        int64
#&gt; hour                            int64
#&gt; minute                          int64
#&gt; time_hour         datetime64[ns, UTC]
#&gt; dtype: object</code></pre>
<ul>
<li><p><code>int64</code> stands for integers.</p></li>
<li><p><code>float64</code> stands for doubles, or real numbers.</p></li>
<li><p><code>object</code> stands for character vectors, or strings.</p></li>
<li><p><code>datetime64</code> stands for date-times (a date + a time) and dates. You can read <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html">more about pandas datetime tools</a></p></li>
</ul>
<p>There are three other common types of variables that aren’t used in this dataset but you’ll encounter later in the book:</p>
<ul>
<li><p><code>bool</code> stands for logical, vectors that contain only <code>True</code> or <code>False</code>.</p></li>
<li><p><code>category</code> stands for factors, which pandas uses to represent categorical variables
with fixed possible values.</p></li>
</ul>
</div>
<div id="pandas-data-manipulation-basics" class="section level3" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> pandas data manipulation basics</h3>
<!-- https://pandas.pydata.org/pandas-docs/stable/getting_started/basics.html -->
<!-- https://www.dataquest.io/blog/pandas-cheat-sheet/ -->
<!-- https://medium.com/dunder-data/minimally-sufficient-pandas-a8e67f2a2428 -->
<p>In this chapter you are going to learn five key pandas functions or object methods. Object methods are things the objects can perform. For example, pandas data frames know how to tell you their shape, the pandas object knows how to concatenate two data frames together. The way we tell an object we want it to do something is with the ‘dot operator’. Below are the five methods that allow you to solve the vast majority of your data manipulation challenges:</p>
<ul>
<li>Pick observations by their values (<code>query()</code>).</li>
<li>Reorder the rows (<code>sort()</code>).</li>
<li>Pick variables by their names (<code>select()</code>).</li>
<li>Create new variables with functions of existing variables (<code>assign()</code>).</li>
<li>Collapse many values down to a single summary (<code>groupby()</code>).</li>
</ul>
<p>The pandas package can handle all of the same functionality of dplyr in R. You can read <a href="https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html">pandas mapping guide</a> and <a href="https://towardsdatascience.com/tidying-up-pandas-4572bfa38776">this towards data science article</a> to get more details on the following brief table.</p>
<p>R dplyr function | Python pandas function
__________________|_______________________
<code>filter()</code> | <code>query()</code><br />
<code>arrange()</code> | <code>sort_values()</code><br />
<code>select()</code> | <code>filter()</code> or <code>loc[]</code>
<code>rename ()</code> | <code>rename()</code><br />
<code>mutate()</code> | <code>assign()</code><br />
<code>group_by ()</code> | <code>groupby()</code><br />
<code>summarise()</code> | <code>agg()</code></p>
<p>The <code>groupby()</code> changes the scope of each function from operating on the entire dataset to operating on it group-by-group. These functions provide the verbs for a language of data manipulation.</p>
<p>All verbs work similarly:</p>
<ol style="list-style-type: decimal">
<li><p>The first argument is a pandas dataFrame.</p></li>
<li><p>The subsequent methods describe what to do with the data frame.</p></li>
<li><p>The result is a new data frame.</p></li>
</ol>
<p>Together these properties make it easy to chain together multiple simple steps to achieve a complex result. Let’s dive in and see how these verbs work.</p>
</div>
</div>
<div id="filter-rows-with-query" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Filter rows with <code>query()</code></h2>
<p><code>query()</code> allows you to subset observations based on their values. The first argument specifies the rows to be selected. This argument can be label names or a boolean series. The second argument specifies the columns to be selected. The bolean filter on the rows is our focus. For example, we can select all flights on January 1st with:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb63-1"><a href="transform.html#cb63-1"></a>flights.query(<span class="st">&#39;month == 1 &amp; day == 1&#39;</span>)</span>
<span id="cb63-2"><a href="transform.html#cb63-2"></a><span class="co">#&gt;      year  month  day  ...  hour  minute                 time_hour</span></span>
<span id="cb63-3"><a href="transform.html#cb63-3"></a><span class="co">#&gt; 0    2013      1    1  ...     5      15 2013-01-01 10:00:00+00:00</span></span>
<span id="cb63-4"><a href="transform.html#cb63-4"></a><span class="co">#&gt; 1    2013      1    1  ...     5      29 2013-01-01 10:00:00+00:00</span></span>
<span id="cb63-5"><a href="transform.html#cb63-5"></a><span class="co">#&gt; 2    2013      1    1  ...     5      40 2013-01-01 10:00:00+00:00</span></span>
<span id="cb63-6"><a href="transform.html#cb63-6"></a><span class="co">#&gt; 3    2013      1    1  ...     5      45 2013-01-01 10:00:00+00:00</span></span>
<span id="cb63-7"><a href="transform.html#cb63-7"></a><span class="co">#&gt; 4    2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb63-8"><a href="transform.html#cb63-8"></a><span class="co">#&gt; ..    ...    ...  ...  ...   ...     ...                       ...</span></span>
<span id="cb63-9"><a href="transform.html#cb63-9"></a><span class="co">#&gt; 837  2013      1    1  ...    23      59 2013-01-02 04:00:00+00:00</span></span>
<span id="cb63-10"><a href="transform.html#cb63-10"></a><span class="co">#&gt; 838  2013      1    1  ...    16      30 2013-01-01 21:00:00+00:00</span></span>
<span id="cb63-11"><a href="transform.html#cb63-11"></a><span class="co">#&gt; 839  2013      1    1  ...    19      35 2013-01-02 00:00:00+00:00</span></span>
<span id="cb63-12"><a href="transform.html#cb63-12"></a><span class="co">#&gt; 840  2013      1    1  ...    15       0 2013-01-01 20:00:00+00:00</span></span>
<span id="cb63-13"><a href="transform.html#cb63-13"></a><span class="co">#&gt; 841  2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb63-14"><a href="transform.html#cb63-14"></a><span class="co">#&gt; </span></span>
<span id="cb63-15"><a href="transform.html#cb63-15"></a><span class="co">#&gt; [842 rows x 19 columns]</span></span></code></pre></div>
<p>The previous expression is equivalent to <code>flights[(flights.month == 1) &amp; (flights.day == 1)]</code></p>
<p>When you run that line of code, pandas executes the filtering operation and returns a new data frame. pandas functions usually don’t modify their inputs, so if you want to save the result, you’ll need to use the assignment operator, <code>=</code>:</p>
<pre class="pandas"><code>jan1 = flights.query(&#39;month == 1 &amp; day == 1&#39;)</code></pre>
<p>Interactive Python either prints out the results, or saves them to a variable.</p>
<div id="comparisons" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Comparisons</h3>
<p>To use filtering effectively, you have to know how to select the observations that you want using the comparison operators. Python provides the standard suite: <code>&gt;</code>, <code>&gt;=</code>, <code>&lt;</code>, <code>&lt;=</code>, <code>!=</code> (not equal), and <code>==</code> (equal).</p>
<p>When you’re starting out with Python, the easiest mistake to make is to use <code>=</code> instead of <code>==</code> when testing for equality. When this happens you’ll get an error:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="transform.html#cb65-1"></a>flights.query(<span class="st">&#39;month = 1&#39;</span>)</span>
<span id="cb65-2"><a href="transform.html#cb65-2"></a><span class="co">#&gt; Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: cannot assign without a target object</span></span>
<span id="cb65-3"><a href="transform.html#cb65-3"></a><span class="co">#&gt; </span></span>
<span id="cb65-4"><a href="transform.html#cb65-4"></a><span class="co">#&gt; Detailed traceback: </span></span>
<span id="cb65-5"><a href="transform.html#cb65-5"></a><span class="co">#&gt;   File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;</span></span>
<span id="cb65-6"><a href="transform.html#cb65-6"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/frame.py&quot;, line 3231, in query</span></span>
<span id="cb65-7"><a href="transform.html#cb65-7"></a><span class="co">#&gt;     res = self.eval(expr, **kwargs)</span></span>
<span id="cb65-8"><a href="transform.html#cb65-8"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/frame.py&quot;, line 3346, in eval</span></span>
<span id="cb65-9"><a href="transform.html#cb65-9"></a><span class="co">#&gt;     return _eval(expr, inplace=inplace, **kwargs)</span></span>
<span id="cb65-10"><a href="transform.html#cb65-10"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/eval.py&quot;, line 332, in eval</span></span>
<span id="cb65-11"><a href="transform.html#cb65-11"></a><span class="co">#&gt;     parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)</span></span>
<span id="cb65-12"><a href="transform.html#cb65-12"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 764, in __init__</span></span>
<span id="cb65-13"><a href="transform.html#cb65-13"></a><span class="co">#&gt;     self.terms = self.parse()</span></span>
<span id="cb65-14"><a href="transform.html#cb65-14"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 781, in parse</span></span>
<span id="cb65-15"><a href="transform.html#cb65-15"></a><span class="co">#&gt;     return self._visitor.visit(self.expr)</span></span>
<span id="cb65-16"><a href="transform.html#cb65-16"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 375, in visit</span></span>
<span id="cb65-17"><a href="transform.html#cb65-17"></a><span class="co">#&gt;     return visitor(node, **kwargs)</span></span>
<span id="cb65-18"><a href="transform.html#cb65-18"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 381, in visit_Module</span></span>
<span id="cb65-19"><a href="transform.html#cb65-19"></a><span class="co">#&gt;     return self.visit(expr, **kwargs)</span></span>
<span id="cb65-20"><a href="transform.html#cb65-20"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 375, in visit</span></span>
<span id="cb65-21"><a href="transform.html#cb65-21"></a><span class="co">#&gt;     return visitor(node, **kwargs)</span></span>
<span id="cb65-22"><a href="transform.html#cb65-22"></a><span class="co">#&gt;   File &quot;/usr/local/lib/python3.7/site-packages/pandas/core/computation/expr.py&quot;, line 585, in visit_Assign</span></span>
<span id="cb65-23"><a href="transform.html#cb65-23"></a><span class="co">#&gt;     raise ValueError(&quot;cannot assign without a target object&quot;)</span></span></code></pre></div>
<p>There’s another common problem you might encounter when using <code>==</code>: floating point numbers. The following result might surprise you!</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb66-1"><a href="transform.html#cb66-1"></a>np.sqrt(<span class="dv">2</span>) <span class="op">**</span> <span class="dv">2</span> <span class="op">==</span>  <span class="dv">2</span></span>
<span id="cb66-2"><a href="transform.html#cb66-2"></a><span class="co">#&gt; False</span></span>
<span id="cb66-3"><a href="transform.html#cb66-3"></a><span class="dv">1</span> <span class="op">/</span> <span class="dv">49</span> <span class="op">*</span> <span class="dv">49</span> <span class="op">==</span> <span class="dv">1</span></span>
<span id="cb66-4"><a href="transform.html#cb66-4"></a><span class="co">#&gt; False</span></span></code></pre></div>
<p>Computers use finite precision arithmetic (they obviously can’t store an infinite number of digits!) so remember that every number you see is an approximation. Instead of relying on <code>==</code>, use <code>np.isclose()</code>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb67-1"><a href="transform.html#cb67-1"></a>np.isclose(np.sqrt(<span class="dv">2</span>) <span class="op">**</span> <span class="dv">2</span>,  <span class="dv">2</span>)</span>
<span id="cb67-2"><a href="transform.html#cb67-2"></a><span class="co">#&gt; True</span></span>
<span id="cb67-3"><a href="transform.html#cb67-3"></a>np.isclose(<span class="dv">1</span> <span class="op">/</span> <span class="dv">49</span> <span class="op">*</span> <span class="dv">49</span>, <span class="dv">1</span>)</span>
<span id="cb67-4"><a href="transform.html#cb67-4"></a><span class="co">#&gt; True</span></span></code></pre></div>
</div>
<div id="logical-operators" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Logical operators</h3>
<p>Multiple arguments to <code>query()</code> are combined with “and”: every expression must be true in order for a row to be included in the output. For other types of combinations, you’ll need to use Boolean operators yourself: <code>&amp;</code> is “and”, <code>|</code> is “or”, and <code>!</code> is “not”. Figure <a href="transform.html#fig:bool-ops">5.1</a> shows the complete set of Boolean operations.</p>
<div class="figure" style="text-align: center"><span id="fig:bool-ops"></span>
<img src="diagrams/transform-logical.png" alt="Complete set of boolean operations. `x` is the left-hand circle, `y` is the right-hand circle, and the shaded region show which parts each operator selects." width="70%" />
<p class="caption">
Figure 5.1: Complete set of boolean operations. <code>x</code> is the left-hand circle, <code>y</code> is the right-hand circle, and the shaded region show which parts each operator selects.
</p>
</div>
<p>The following code finds all flights that departed in November or December:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb68-1"><a href="transform.html#cb68-1"></a>flights.query(<span class="st">&#39;month == 11 | month == 12&#39;</span>)</span></code></pre></div>
<p>The order of operations doesn’t work like English. You can’t write <code>filter(flights, month == (11 | 12))</code>, which you might literally translate into “finds all flights that departed in November or December”. Instead it finds all months that equal <code>11 | 12</code>, an expression that evaluates to <code>True</code>. In a numeric context (like here), <code>True</code> becomes one, so this finds all flights in January, not November or December. This is quite confusing!</p>
<p>A useful short-hand for this problem is <code>x in y</code>. This will select every row where <code>x</code> is one of the values in <code>y</code>. We could use it to rewrite the code above:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb69-1"><a href="transform.html#cb69-1"></a>nov_dec <span class="op">=</span> flights.query(<span class="st">&#39;month in [11, 12]&#39;</span>)</span></code></pre></div>
<p>Sometimes you can simplify complicated subsetting by remembering De Morgan’s law: <code>!(x &amp; y)</code> is the same as <code>!x | !y</code>, and <code>!(x | y)</code> is the same as <code>!x &amp; !y</code>. For example, if you wanted to find flights that weren’t delayed (on arrival or departure) by more than two hours, you could use either of the following two filters:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb70-1"><a href="transform.html#cb70-1"></a>flights.query(<span class="st">&#39;arr_delay &gt; 120 | dep_delay &gt; 120&#39;</span>)</span>
<span id="cb70-2"><a href="transform.html#cb70-2"></a>flights.query(<span class="st">&#39;arr_delay &lt;= 120 | dep_delay &lt;= 120&#39;</span>)</span></code></pre></div>
<!-- As well as `&` and `|`, Python also has `&&` and `||`. Don't use them here! You'll learn when you should use them in [conditional execution]. -->
<p>Whenever you start using complicated, multipart expressions in <code>query()</code>, consider making them explicit variables instead. That makes it much easier to check your work. You’ll learn how to create new variables shortly.</p>
</div>
<div id="missing-values" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Missing values</h3>
<p>One important feature of pandas in Python that can make comparison tricky are missing values, or <code>NA</code>s (“not availables”). <code>NA</code> represents an unknown value so missing values are “contagious”: almost any operation involving an unknown value will also be unknown.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb71-1"><a href="transform.html#cb71-1"></a>np.nan <span class="op">+</span> <span class="dv">10</span></span>
<span id="cb71-2"><a href="transform.html#cb71-2"></a><span class="co">#&gt; nan</span></span>
<span id="cb71-3"><a href="transform.html#cb71-3"></a>np.nan <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb71-4"><a href="transform.html#cb71-4"></a><span class="co">#&gt; nan</span></span></code></pre></div>
<p>The most confusing result are the comparisons. They always return a <code>False</code>. The logic for this result <a href="https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values">is explained on stackoverflow</a>. The <a href="https://pandas.pydata.org/pandas-docs/dev/user_guide/missing_data.html">pandas missing data guide</a> is a helpful read.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb72-1"><a href="transform.html#cb72-1"></a>np.nan <span class="op">&gt;</span> <span class="dv">5</span></span>
<span id="cb72-2"><a href="transform.html#cb72-2"></a><span class="co">#&gt; False</span></span>
<span id="cb72-3"><a href="transform.html#cb72-3"></a><span class="dv">10</span> <span class="op">==</span> np.nan</span>
<span id="cb72-4"><a href="transform.html#cb72-4"></a><span class="co">#&gt; False</span></span>
<span id="cb72-5"><a href="transform.html#cb72-5"></a>np.nan <span class="op">==</span> np.nan</span>
<span id="cb72-6"><a href="transform.html#cb72-6"></a><span class="co">#&gt; False</span></span></code></pre></div>
<p>It’s easiest to understand why this is true with a bit more context:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb73-1"><a href="transform.html#cb73-1"></a><span class="co"># Let x be Mary&#39;s age. We don&#39;t know how old she is.</span></span>
<span id="cb73-2"><a href="transform.html#cb73-2"></a>x <span class="op">=</span> np.nan</span>
<span id="cb73-3"><a href="transform.html#cb73-3"></a></span>
<span id="cb73-4"><a href="transform.html#cb73-4"></a><span class="co"># Let y be John&#39;s age. We don&#39;t know how old he is.</span></span>
<span id="cb73-5"><a href="transform.html#cb73-5"></a>y <span class="op">=</span> np.nan</span>
<span id="cb73-6"><a href="transform.html#cb73-6"></a></span>
<span id="cb73-7"><a href="transform.html#cb73-7"></a><span class="co"># Are John and Mary the same age?</span></span>
<span id="cb73-8"><a href="transform.html#cb73-8"></a>x <span class="op">==</span> y</span>
<span id="cb73-9"><a href="transform.html#cb73-9"></a><span class="co"># Illogical comparisons are False.</span></span>
<span id="cb73-10"><a href="transform.html#cb73-10"></a><span class="co">#&gt; False</span></span></code></pre></div>
<p>The Python development team did decide to provide functionality to find <code>np.nan</code> objects in your code by allowing <code>np.nan != np.nan</code> to return <code>True</code>. Once again you can <a href="https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values">read the rationale for this decision</a>. Python now has <code>isnan()</code> functions to make this comparison more straight forward in your code.</p>
<p>Pandas uses the <code>nan</code> structure in Python to identify <strong>NA</strong> or ‘missing’ values. If you want to determine if a value is missing, use <code>pd.isna()</code>:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb74-1"><a href="transform.html#cb74-1"></a>pd.isna(x)</span>
<span id="cb74-2"><a href="transform.html#cb74-2"></a><span class="co">#&gt; True</span></span></code></pre></div>
<p><code>query()</code> only includes rows where the condition is <code>TRUE</code>; it excludes both <code>FALSE</code> and <strong>NA</strong> values.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb75-1"><a href="transform.html#cb75-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">&#39;x&#39;</span>: [<span class="dv">1</span>, np.nan, <span class="dv">3</span>]})</span>
<span id="cb75-2"><a href="transform.html#cb75-2"></a>df.query(<span class="st">&#39;x &gt; 1&#39;</span>)</span>
<span id="cb75-3"><a href="transform.html#cb75-3"></a><span class="co">#&gt;      x</span></span>
<span id="cb75-4"><a href="transform.html#cb75-4"></a><span class="co">#&gt; 2  3.0</span></span></code></pre></div>
<p>If you want to preserve missing values, ask for them explicitly using the trick mentioned in the previous paragraph or by using <code>pd.isna()</code> with the symbolic reference <code>@</code> in your condition:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb76-1"><a href="transform.html#cb76-1"></a>df.query(<span class="st">&#39;x != x | x &gt; 1&#39;</span>)</span>
<span id="cb76-2"><a href="transform.html#cb76-2"></a><span class="co">#&gt;      x</span></span>
<span id="cb76-3"><a href="transform.html#cb76-3"></a><span class="co">#&gt; 1  NaN</span></span>
<span id="cb76-4"><a href="transform.html#cb76-4"></a><span class="co">#&gt; 2  3.0</span></span>
<span id="cb76-5"><a href="transform.html#cb76-5"></a>df.query(<span class="st">&#39;@pd.isna(x) | x &gt; 1&#39;</span>)</span>
<span id="cb76-6"><a href="transform.html#cb76-6"></a><span class="co">#&gt;      x</span></span>
<span id="cb76-7"><a href="transform.html#cb76-7"></a><span class="co">#&gt; 1  NaN</span></span>
<span id="cb76-8"><a href="transform.html#cb76-8"></a><span class="co">#&gt; 2  3.0</span></span></code></pre></div>
</div>
<div id="exercises-5" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Find all flights that</p>
<ol style="list-style-type: decimal">
<li>Had an arrival delay of two or more hours</li>
<li>Flew to Houston (<code>IAH</code> or <code>HOU</code>)</li>
<li>Were operated by United, American, or Delta</li>
<li>Departed in summer (July, August, and September)</li>
<li>Arrived more than two hours late, but didn’t leave late</li>
<li>Were delayed by at least an hour, but made up over 30 minutes in flight</li>
<li>Departed between midnight and 6am (inclusive)</li>
</ol></li>
<li><p>How many flights have a missing <code>dep_time</code>? What other variables are
missing? What might these rows represent?</p></li>
</ol>
</div>
</div>
<div id="arrange-or-sort-rows-with-sort_values" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Arrange or sort rows with <code>sort_values()</code></h2>
<p><code>sort()</code> works similarly to <code>query()</code> except that instead of selecting rows, it changes their order. It takes a data frame and a column name or a list of column names to order by. If you provide more than one column name, each additional column will be used to break ties in the values of preceding columns:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb77-1"><a href="transform.html#cb77-1"></a>flights.sort_values(by <span class="op">=</span> [<span class="st">&#39;year&#39;</span>, <span class="st">&#39;month&#39;</span>, <span class="st">&#39;day&#39;</span>])</span>
<span id="cb77-2"><a href="transform.html#cb77-2"></a><span class="co">#&gt;         year  month  day  ...  hour  minute                 time_hour</span></span>
<span id="cb77-3"><a href="transform.html#cb77-3"></a><span class="co">#&gt; 0       2013      1    1  ...     5      15 2013-01-01 10:00:00+00:00</span></span>
<span id="cb77-4"><a href="transform.html#cb77-4"></a><span class="co">#&gt; 1       2013      1    1  ...     5      29 2013-01-01 10:00:00+00:00</span></span>
<span id="cb77-5"><a href="transform.html#cb77-5"></a><span class="co">#&gt; 2       2013      1    1  ...     5      40 2013-01-01 10:00:00+00:00</span></span>
<span id="cb77-6"><a href="transform.html#cb77-6"></a><span class="co">#&gt; 3       2013      1    1  ...     5      45 2013-01-01 10:00:00+00:00</span></span>
<span id="cb77-7"><a href="transform.html#cb77-7"></a><span class="co">#&gt; 4       2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb77-8"><a href="transform.html#cb77-8"></a><span class="co">#&gt; ...      ...    ...  ...  ...   ...     ...                       ...</span></span>
<span id="cb77-9"><a href="transform.html#cb77-9"></a><span class="co">#&gt; 111291  2013     12   31  ...     7       5 2013-12-31 12:00:00+00:00</span></span>
<span id="cb77-10"><a href="transform.html#cb77-10"></a><span class="co">#&gt; 111292  2013     12   31  ...     8      25 2013-12-31 13:00:00+00:00</span></span>
<span id="cb77-11"><a href="transform.html#cb77-11"></a><span class="co">#&gt; 111293  2013     12   31  ...    16      15 2013-12-31 21:00:00+00:00</span></span>
<span id="cb77-12"><a href="transform.html#cb77-12"></a><span class="co">#&gt; 111294  2013     12   31  ...     6       0 2013-12-31 11:00:00+00:00</span></span>
<span id="cb77-13"><a href="transform.html#cb77-13"></a><span class="co">#&gt; 111295  2013     12   31  ...     8      30 2013-12-31 13:00:00+00:00</span></span>
<span id="cb77-14"><a href="transform.html#cb77-14"></a><span class="co">#&gt; </span></span>
<span id="cb77-15"><a href="transform.html#cb77-15"></a><span class="co">#&gt; [336776 rows x 19 columns]</span></span></code></pre></div>
<p>Use the argument <code>ascending = False</code> to re-order by a column in descending order:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb78-1"><a href="transform.html#cb78-1"></a>flights.sort_values(by <span class="op">=</span> [<span class="st">&#39;year&#39;</span>, <span class="st">&#39;month&#39;</span>, <span class="st">&#39;day&#39;</span>], ascending <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb78-2"><a href="transform.html#cb78-2"></a><span class="co">#&gt;         year  month  day  ...  hour  minute                 time_hour</span></span>
<span id="cb78-3"><a href="transform.html#cb78-3"></a><span class="co">#&gt; 110520  2013     12   31  ...    23      59 2014-01-01 04:00:00+00:00</span></span>
<span id="cb78-4"><a href="transform.html#cb78-4"></a><span class="co">#&gt; 110521  2013     12   31  ...    23      59 2014-01-01 04:00:00+00:00</span></span>
<span id="cb78-5"><a href="transform.html#cb78-5"></a><span class="co">#&gt; 110522  2013     12   31  ...    22      45 2014-01-01 03:00:00+00:00</span></span>
<span id="cb78-6"><a href="transform.html#cb78-6"></a><span class="co">#&gt; 110523  2013     12   31  ...     5       0 2013-12-31 10:00:00+00:00</span></span>
<span id="cb78-7"><a href="transform.html#cb78-7"></a><span class="co">#&gt; 110524  2013     12   31  ...     5      15 2013-12-31 10:00:00+00:00</span></span>
<span id="cb78-8"><a href="transform.html#cb78-8"></a><span class="co">#&gt; ...      ...    ...  ...  ...   ...     ...                       ...</span></span>
<span id="cb78-9"><a href="transform.html#cb78-9"></a><span class="co">#&gt; 837     2013      1    1  ...    23      59 2013-01-02 04:00:00+00:00</span></span>
<span id="cb78-10"><a href="transform.html#cb78-10"></a><span class="co">#&gt; 838     2013      1    1  ...    16      30 2013-01-01 21:00:00+00:00</span></span>
<span id="cb78-11"><a href="transform.html#cb78-11"></a><span class="co">#&gt; 839     2013      1    1  ...    19      35 2013-01-02 00:00:00+00:00</span></span>
<span id="cb78-12"><a href="transform.html#cb78-12"></a><span class="co">#&gt; 840     2013      1    1  ...    15       0 2013-01-01 20:00:00+00:00</span></span>
<span id="cb78-13"><a href="transform.html#cb78-13"></a><span class="co">#&gt; 841     2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb78-14"><a href="transform.html#cb78-14"></a><span class="co">#&gt; </span></span>
<span id="cb78-15"><a href="transform.html#cb78-15"></a><span class="co">#&gt; [336776 rows x 19 columns]</span></span></code></pre></div>
<p>Missing values are always sorted at the end:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb79-1"><a href="transform.html#cb79-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">&#39;x&#39;</span>: [<span class="dv">5</span>, <span class="dv">2</span>, np.nan]})</span>
<span id="cb79-2"><a href="transform.html#cb79-2"></a>df.sort_values(<span class="st">&#39;x&#39;</span>)</span>
<span id="cb79-3"><a href="transform.html#cb79-3"></a><span class="co">#&gt;      x</span></span>
<span id="cb79-4"><a href="transform.html#cb79-4"></a><span class="co">#&gt; 1  2.0</span></span>
<span id="cb79-5"><a href="transform.html#cb79-5"></a><span class="co">#&gt; 0  5.0</span></span>
<span id="cb79-6"><a href="transform.html#cb79-6"></a><span class="co">#&gt; 2  NaN</span></span>
<span id="cb79-7"><a href="transform.html#cb79-7"></a>df.sort_values(<span class="st">&#39;x&#39;</span>, ascending <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb79-8"><a href="transform.html#cb79-8"></a><span class="co">#&gt;      x</span></span>
<span id="cb79-9"><a href="transform.html#cb79-9"></a><span class="co">#&gt; 0  5.0</span></span>
<span id="cb79-10"><a href="transform.html#cb79-10"></a><span class="co">#&gt; 1  2.0</span></span>
<span id="cb79-11"><a href="transform.html#cb79-11"></a><span class="co">#&gt; 2  NaN</span></span></code></pre></div>
<div id="exercises-6" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>How could you use <code>sort()</code> to sort all missing values to the start?
(Hint: use <code>isna()</code>).</p>
<!-- df.sort_values('x', ascending = False, na_position = "first") --></li>
<li><p>Sort <code>flights</code> to find the most delayed flights. Find the flights that
left earliest.</p></li>
<li><p>Sort <code>flights</code> to find the fastest (highest speed) flights.</p></li>
<li><p>Which flights travelled the farthest? Which travelled the shortest?</p></li>
</ol>
</div>
</div>
<div id="select" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Select columns with <code>filter()</code> or <code>loc[]</code></h2>
<p>It’s not uncommon to get datasets with hundreds or even thousands of variables. In this case, the first challenge is often narrowing in on the variables you’re actually interested in. <code>fliter()</code> allows you to rapidly zoom in on a useful subset using operations based on the names of the variables.</p>
<p><code>filter()</code> is not terribly useful with the flights data because we only have 19 variables, but you can still get the general idea:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb80-1"><a href="transform.html#cb80-1"></a><span class="co"># Select columns by name</span></span>
<span id="cb80-2"><a href="transform.html#cb80-2"></a>flights.<span class="bu">filter</span>([<span class="st">&#39;year&#39;</span>, <span class="st">&#39;month&#39;</span>, <span class="st">&#39;day&#39;</span>])</span>
<span id="cb80-3"><a href="transform.html#cb80-3"></a><span class="co"># Select all columns except year and day (inclusive)</span></span>
<span id="cb80-4"><a href="transform.html#cb80-4"></a><span class="co">#&gt;         year  month  day</span></span>
<span id="cb80-5"><a href="transform.html#cb80-5"></a><span class="co">#&gt; 0       2013      1    1</span></span>
<span id="cb80-6"><a href="transform.html#cb80-6"></a><span class="co">#&gt; 1       2013      1    1</span></span>
<span id="cb80-7"><a href="transform.html#cb80-7"></a><span class="co">#&gt; 2       2013      1    1</span></span>
<span id="cb80-8"><a href="transform.html#cb80-8"></a><span class="co">#&gt; 3       2013      1    1</span></span>
<span id="cb80-9"><a href="transform.html#cb80-9"></a><span class="co">#&gt; 4       2013      1    1</span></span>
<span id="cb80-10"><a href="transform.html#cb80-10"></a><span class="co">#&gt; ...      ...    ...  ...</span></span>
<span id="cb80-11"><a href="transform.html#cb80-11"></a><span class="co">#&gt; 336771  2013      9   30</span></span>
<span id="cb80-12"><a href="transform.html#cb80-12"></a><span class="co">#&gt; 336772  2013      9   30</span></span>
<span id="cb80-13"><a href="transform.html#cb80-13"></a><span class="co">#&gt; 336773  2013      9   30</span></span>
<span id="cb80-14"><a href="transform.html#cb80-14"></a><span class="co">#&gt; 336774  2013      9   30</span></span>
<span id="cb80-15"><a href="transform.html#cb80-15"></a><span class="co">#&gt; 336775  2013      9   30</span></span>
<span id="cb80-16"><a href="transform.html#cb80-16"></a><span class="co">#&gt; </span></span>
<span id="cb80-17"><a href="transform.html#cb80-17"></a><span class="co">#&gt; [336776 rows x 3 columns]</span></span>
<span id="cb80-18"><a href="transform.html#cb80-18"></a>flights.drop(columns <span class="op">=</span> [<span class="st">&#39;year&#39;</span>, <span class="st">&#39;day&#39;</span>])</span>
<span id="cb80-19"><a href="transform.html#cb80-19"></a><span class="co">#&gt;         month  dep_time  sched_dep_time  ...  hour  minute                 time_hour</span></span>
<span id="cb80-20"><a href="transform.html#cb80-20"></a><span class="co">#&gt; 0           1     517.0             515  ...     5      15 2013-01-01 10:00:00+00:00</span></span>
<span id="cb80-21"><a href="transform.html#cb80-21"></a><span class="co">#&gt; 1           1     533.0             529  ...     5      29 2013-01-01 10:00:00+00:00</span></span>
<span id="cb80-22"><a href="transform.html#cb80-22"></a><span class="co">#&gt; 2           1     542.0             540  ...     5      40 2013-01-01 10:00:00+00:00</span></span>
<span id="cb80-23"><a href="transform.html#cb80-23"></a><span class="co">#&gt; 3           1     544.0             545  ...     5      45 2013-01-01 10:00:00+00:00</span></span>
<span id="cb80-24"><a href="transform.html#cb80-24"></a><span class="co">#&gt; 4           1     554.0             600  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb80-25"><a href="transform.html#cb80-25"></a><span class="co">#&gt; ...       ...       ...             ...  ...   ...     ...                       ...</span></span>
<span id="cb80-26"><a href="transform.html#cb80-26"></a><span class="co">#&gt; 336771      9       NaN            1455  ...    14      55 2013-09-30 18:00:00+00:00</span></span>
<span id="cb80-27"><a href="transform.html#cb80-27"></a><span class="co">#&gt; 336772      9       NaN            2200  ...    22       0 2013-10-01 02:00:00+00:00</span></span>
<span id="cb80-28"><a href="transform.html#cb80-28"></a><span class="co">#&gt; 336773      9       NaN            1210  ...    12      10 2013-09-30 16:00:00+00:00</span></span>
<span id="cb80-29"><a href="transform.html#cb80-29"></a><span class="co">#&gt; 336774      9       NaN            1159  ...    11      59 2013-09-30 15:00:00+00:00</span></span>
<span id="cb80-30"><a href="transform.html#cb80-30"></a><span class="co">#&gt; 336775      9       NaN             840  ...     8      40 2013-09-30 12:00:00+00:00</span></span>
<span id="cb80-31"><a href="transform.html#cb80-31"></a><span class="co">#&gt; </span></span>
<span id="cb80-32"><a href="transform.html#cb80-32"></a><span class="co">#&gt; [336776 rows x 17 columns]</span></span></code></pre></div>
<p><code>loc[]</code> functions in a similar fashion.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb81-1"><a href="transform.html#cb81-1"></a><span class="co"># Select columns by name</span></span>
<span id="cb81-2"><a href="transform.html#cb81-2"></a>flights.loc[:, [<span class="st">&#39;year&#39;</span>, <span class="st">&#39;month&#39;</span>, <span class="st">&#39;day&#39;</span>]]</span>
<span id="cb81-3"><a href="transform.html#cb81-3"></a><span class="co"># Select all columns between year and day (inclusive)</span></span>
<span id="cb81-4"><a href="transform.html#cb81-4"></a><span class="co">#&gt;         year  month  day</span></span>
<span id="cb81-5"><a href="transform.html#cb81-5"></a><span class="co">#&gt; 0       2013      1    1</span></span>
<span id="cb81-6"><a href="transform.html#cb81-6"></a><span class="co">#&gt; 1       2013      1    1</span></span>
<span id="cb81-7"><a href="transform.html#cb81-7"></a><span class="co">#&gt; 2       2013      1    1</span></span>
<span id="cb81-8"><a href="transform.html#cb81-8"></a><span class="co">#&gt; 3       2013      1    1</span></span>
<span id="cb81-9"><a href="transform.html#cb81-9"></a><span class="co">#&gt; 4       2013      1    1</span></span>
<span id="cb81-10"><a href="transform.html#cb81-10"></a><span class="co">#&gt; ...      ...    ...  ...</span></span>
<span id="cb81-11"><a href="transform.html#cb81-11"></a><span class="co">#&gt; 336771  2013      9   30</span></span>
<span id="cb81-12"><a href="transform.html#cb81-12"></a><span class="co">#&gt; 336772  2013      9   30</span></span>
<span id="cb81-13"><a href="transform.html#cb81-13"></a><span class="co">#&gt; 336773  2013      9   30</span></span>
<span id="cb81-14"><a href="transform.html#cb81-14"></a><span class="co">#&gt; 336774  2013      9   30</span></span>
<span id="cb81-15"><a href="transform.html#cb81-15"></a><span class="co">#&gt; 336775  2013      9   30</span></span>
<span id="cb81-16"><a href="transform.html#cb81-16"></a><span class="co">#&gt; </span></span>
<span id="cb81-17"><a href="transform.html#cb81-17"></a><span class="co">#&gt; [336776 rows x 3 columns]</span></span>
<span id="cb81-18"><a href="transform.html#cb81-18"></a>flights.loc[:, <span class="st">&#39;year&#39;</span>:<span class="st">&#39;day&#39;</span>]</span>
<span id="cb81-19"><a href="transform.html#cb81-19"></a><span class="co"># Select all columns except year and day (inclusive)</span></span>
<span id="cb81-20"><a href="transform.html#cb81-20"></a><span class="co">#&gt;         year  month  day</span></span>
<span id="cb81-21"><a href="transform.html#cb81-21"></a><span class="co">#&gt; 0       2013      1    1</span></span>
<span id="cb81-22"><a href="transform.html#cb81-22"></a><span class="co">#&gt; 1       2013      1    1</span></span>
<span id="cb81-23"><a href="transform.html#cb81-23"></a><span class="co">#&gt; 2       2013      1    1</span></span>
<span id="cb81-24"><a href="transform.html#cb81-24"></a><span class="co">#&gt; 3       2013      1    1</span></span>
<span id="cb81-25"><a href="transform.html#cb81-25"></a><span class="co">#&gt; 4       2013      1    1</span></span>
<span id="cb81-26"><a href="transform.html#cb81-26"></a><span class="co">#&gt; ...      ...    ...  ...</span></span>
<span id="cb81-27"><a href="transform.html#cb81-27"></a><span class="co">#&gt; 336771  2013      9   30</span></span>
<span id="cb81-28"><a href="transform.html#cb81-28"></a><span class="co">#&gt; 336772  2013      9   30</span></span>
<span id="cb81-29"><a href="transform.html#cb81-29"></a><span class="co">#&gt; 336773  2013      9   30</span></span>
<span id="cb81-30"><a href="transform.html#cb81-30"></a><span class="co">#&gt; 336774  2013      9   30</span></span>
<span id="cb81-31"><a href="transform.html#cb81-31"></a><span class="co">#&gt; 336775  2013      9   30</span></span>
<span id="cb81-32"><a href="transform.html#cb81-32"></a><span class="co">#&gt; </span></span>
<span id="cb81-33"><a href="transform.html#cb81-33"></a><span class="co">#&gt; [336776 rows x 3 columns]</span></span></code></pre></div>
<p>There are a number of helper regular expressions you can use within <code>filter()</code>:</p>
<ul>
<li><p><code>flights.filter(regex = '^sch')</code>: matches column names that begin with “sch”.</p></li>
<li><p><code>flights.filter(regex = "time$")</code>: matches names that end with “time”.</p></li>
<li><p><code>flights.filter(regex = "_dep_")</code>: matches names that contain “<em>dep</em>”.</p></li>
<li><p><code>flights.filter(regex = '(.)\\1')</code>: selects variables that match a regular expression.
This one matches any variables that contain repeated characters. You’ll
learn more about regular expressions in [strings].</p></li>
</ul>
<p>See <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.filter.html">pandas filter documentation</a> for more details.</p>
<p>Use <code>rename()</code> to rename a column or multiple columns.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb82-1"><a href="transform.html#cb82-1"></a>flights.rename(columns <span class="op">=</span> {<span class="st">&#39;year&#39;</span>: <span class="st">&#39;YEAR&#39;</span>, <span class="st">&#39;month&#39;</span>:<span class="st">&#39;MONTH&#39;</span>})</span>
<span id="cb82-2"><a href="transform.html#cb82-2"></a><span class="co">#&gt;         YEAR  MONTH  day  ...  hour  minute                 time_hour</span></span>
<span id="cb82-3"><a href="transform.html#cb82-3"></a><span class="co">#&gt; 0       2013      1    1  ...     5      15 2013-01-01 10:00:00+00:00</span></span>
<span id="cb82-4"><a href="transform.html#cb82-4"></a><span class="co">#&gt; 1       2013      1    1  ...     5      29 2013-01-01 10:00:00+00:00</span></span>
<span id="cb82-5"><a href="transform.html#cb82-5"></a><span class="co">#&gt; 2       2013      1    1  ...     5      40 2013-01-01 10:00:00+00:00</span></span>
<span id="cb82-6"><a href="transform.html#cb82-6"></a><span class="co">#&gt; 3       2013      1    1  ...     5      45 2013-01-01 10:00:00+00:00</span></span>
<span id="cb82-7"><a href="transform.html#cb82-7"></a><span class="co">#&gt; 4       2013      1    1  ...     6       0 2013-01-01 11:00:00+00:00</span></span>
<span id="cb82-8"><a href="transform.html#cb82-8"></a><span class="co">#&gt; ...      ...    ...  ...  ...   ...     ...                       ...</span></span>
<span id="cb82-9"><a href="transform.html#cb82-9"></a><span class="co">#&gt; 336771  2013      9   30  ...    14      55 2013-09-30 18:00:00+00:00</span></span>
<span id="cb82-10"><a href="transform.html#cb82-10"></a><span class="co">#&gt; 336772  2013      9   30  ...    22       0 2013-10-01 02:00:00+00:00</span></span>
<span id="cb82-11"><a href="transform.html#cb82-11"></a><span class="co">#&gt; 336773  2013      9   30  ...    12      10 2013-09-30 16:00:00+00:00</span></span>
<span id="cb82-12"><a href="transform.html#cb82-12"></a><span class="co">#&gt; 336774  2013      9   30  ...    11      59 2013-09-30 15:00:00+00:00</span></span>
<span id="cb82-13"><a href="transform.html#cb82-13"></a><span class="co">#&gt; 336775  2013      9   30  ...     8      40 2013-09-30 12:00:00+00:00</span></span>
<span id="cb82-14"><a href="transform.html#cb82-14"></a><span class="co">#&gt; </span></span>
<span id="cb82-15"><a href="transform.html#cb82-15"></a><span class="co">#&gt; [336776 rows x 19 columns]</span></span></code></pre></div>
<div id="exercises-7" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Brainstorm as many ways as possible to select <code>dep_time</code>, <code>dep_delay</code>,
<code>arr_time</code>, and <code>arr_delay</code> from <code>flights</code>.</p></li>
<li><p>What happens if you include the name of a variable multiple times in
a <code>filter()</code> call?</p></li>
<li><p>Does the result of running the following code surprise you? How do the
select helpers deal with case by default? How can you change that default?</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="transform.html#cb83-1"></a><span class="kw">flights.filter</span>(<span class="dt">regex =</span> <span class="st">&quot;TIME&quot;</span>)</span></code></pre></div></li>
</ol>
</div>
</div>
<div id="add-new-variables-with-assign" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Add new variables with <code>assign()</code></h2>
<p>Besides selecting sets of existing columns, it’s often useful to add new columns that are functions of existing columns. That’s the job of <code>assign()</code>.</p>
<p><code>assign()</code> always adds new columns at the end of your dataset so we’ll start by creating a narrower dataset so we can see the new variables.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb84-1"><a href="transform.html#cb84-1"></a></span>
<span id="cb84-2"><a href="transform.html#cb84-2"></a>flights_sml <span class="op">=</span> (flights.</span>
<span id="cb84-3"><a href="transform.html#cb84-3"></a>    <span class="bu">filter</span>(regex <span class="op">=</span> <span class="st">&quot;^year$|^month$|^day$|delay$|^distance$|^air_time$&quot;</span>)</span>
<span id="cb84-4"><a href="transform.html#cb84-4"></a>)</span>
<span id="cb84-5"><a href="transform.html#cb84-5"></a></span>
<span id="cb84-6"><a href="transform.html#cb84-6"></a>flights_sml.assign(</span>
<span id="cb84-7"><a href="transform.html#cb84-7"></a>    gain <span class="op">=</span> <span class="kw">lambda</span> x: x.dep_delay <span class="op">-</span> x.arr_delay,</span>
<span id="cb84-8"><a href="transform.html#cb84-8"></a>    speed <span class="op">=</span> <span class="kw">lambda</span> x: x.distance <span class="op">/</span> x.air_time <span class="op">*</span> <span class="dv">60</span></span>
<span id="cb84-9"><a href="transform.html#cb84-9"></a>    ).head()</span>
<span id="cb84-10"><a href="transform.html#cb84-10"></a><span class="co">#&gt;    year  month  day  dep_delay  arr_delay  air_time  distance  gain       speed</span></span>
<span id="cb84-11"><a href="transform.html#cb84-11"></a><span class="co">#&gt; 0  2013      1    1        2.0       11.0     227.0      1400  -9.0  370.044053</span></span>
<span id="cb84-12"><a href="transform.html#cb84-12"></a><span class="co">#&gt; 1  2013      1    1        4.0       20.0     227.0      1416 -16.0  374.273128</span></span>
<span id="cb84-13"><a href="transform.html#cb84-13"></a><span class="co">#&gt; 2  2013      1    1        2.0       33.0     160.0      1089 -31.0  408.375000</span></span>
<span id="cb84-14"><a href="transform.html#cb84-14"></a><span class="co">#&gt; 3  2013      1    1       -1.0      -18.0     183.0      1576  17.0  516.721311</span></span>
<span id="cb84-15"><a href="transform.html#cb84-15"></a><span class="co">#&gt; 4  2013      1    1       -6.0      -25.0     116.0       762  19.0  394.137931</span></span></code></pre></div>
<p>Note that you can refer to columns that you’ve just created:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb85-1"><a href="transform.html#cb85-1"></a>flights_sml.assign(</span>
<span id="cb85-2"><a href="transform.html#cb85-2"></a>    gain <span class="op">=</span> <span class="kw">lambda</span> x: x.dep_delay <span class="op">-</span> x.arr_delay,</span>
<span id="cb85-3"><a href="transform.html#cb85-3"></a>    hours <span class="op">=</span> <span class="kw">lambda</span> x: x.air_time <span class="op">/</span> <span class="dv">60</span>,</span>
<span id="cb85-4"><a href="transform.html#cb85-4"></a>    gain_per_hour <span class="op">=</span> <span class="kw">lambda</span> x: x.gain <span class="op">/</span> x.hours</span>
<span id="cb85-5"><a href="transform.html#cb85-5"></a>).head()</span>
<span id="cb85-6"><a href="transform.html#cb85-6"></a><span class="co">#&gt;    year  month  day  dep_delay  ...  distance  gain     hours  gain_per_hour</span></span>
<span id="cb85-7"><a href="transform.html#cb85-7"></a><span class="co">#&gt; 0  2013      1    1        2.0  ...      1400  -9.0  3.783333      -2.378855</span></span>
<span id="cb85-8"><a href="transform.html#cb85-8"></a><span class="co">#&gt; 1  2013      1    1        4.0  ...      1416 -16.0  3.783333      -4.229075</span></span>
<span id="cb85-9"><a href="transform.html#cb85-9"></a><span class="co">#&gt; 2  2013      1    1        2.0  ...      1089 -31.0  2.666667     -11.625000</span></span>
<span id="cb85-10"><a href="transform.html#cb85-10"></a><span class="co">#&gt; 3  2013      1    1       -1.0  ...      1576  17.0  3.050000       5.573770</span></span>
<span id="cb85-11"><a href="transform.html#cb85-11"></a><span class="co">#&gt; 4  2013      1    1       -6.0  ...       762  19.0  1.933333       9.827586</span></span>
<span id="cb85-12"><a href="transform.html#cb85-12"></a><span class="co">#&gt; </span></span>
<span id="cb85-13"><a href="transform.html#cb85-13"></a><span class="co">#&gt; [5 rows x 10 columns]</span></span></code></pre></div>
<div id="mutate-funs" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Useful creation functions</h3>
<p>There are many functions for creating new variables that you can use with <code>assign()</code>. The key property is that the function must be vectorised: it must take a vector of values as input, return a vector with the same number of values as output. Some arithmetic operators are available in Python without the need for any additional packages. However, many arithmetic functions like <code>mean()</code> and <code>std()</code> are accessed through importing additional packages. Python comes with a <code>math</code> and <code>statistics</code> package. However, we recommend the <strong>NumPy</strong> package for accessing the suite of mathematical functions needed. You would import NumPy with <code>import numpy as np</code>. There’s no way to list every possible function that you might use, but here’s a selection of functions that are frequently useful:</p>
<ul>
<li><p>Arithmetic operators: <code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, <code>^</code>. These are all vectorised,
using the so called “recycling rules”. If one parameter is shorter than
the other, it will be automatically extended to be the same length. This
is most useful when one of the arguments is a single number: <code>air_time / 60</code>,
<code>hours * 60 + minute</code>, etc.</p>
<p>Arithmetic operators are also useful in conjunction with the aggregate
functions you’ll learn about later. For example, <code>x / np.sum(x)</code> calculates
the proportion of a total, and <code>y - np.mean(y)</code> computes the difference from
the mean.</p></li>
<li><p>Modular arithmetic: <code>//</code> (integer division) and <code>%</code> (remainder), where
<code>x == y * (x // y) + (x % y)</code>. Modular arithmetic is a handy tool because
it allows you to break integers up into pieces. For example, in the
flights dataset, you can compute <code>hour</code> and <code>minute</code> from <code>dep_time</code> with:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb86-1"><a href="transform.html#cb86-1"></a>(flights.</span>
<span id="cb86-2"><a href="transform.html#cb86-2"></a>    <span class="bu">filter</span>([<span class="st">&#39;dep_time&#39;</span>]).</span>
<span id="cb86-3"><a href="transform.html#cb86-3"></a>    assign(</span>
<span id="cb86-4"><a href="transform.html#cb86-4"></a>      hour <span class="op">=</span> <span class="kw">lambda</span> x: x.dep_time <span class="op">//</span> <span class="dv">100</span>,</span>
<span id="cb86-5"><a href="transform.html#cb86-5"></a>      minute <span class="op">=</span> <span class="kw">lambda</span> x: x.dep_time <span class="op">%</span> <span class="dv">100</span>)</span>
<span id="cb86-6"><a href="transform.html#cb86-6"></a>)</span>
<span id="cb86-7"><a href="transform.html#cb86-7"></a><span class="co">#&gt;         dep_time  hour  minute</span></span>
<span id="cb86-8"><a href="transform.html#cb86-8"></a><span class="co">#&gt; 0          517.0   5.0    17.0</span></span>
<span id="cb86-9"><a href="transform.html#cb86-9"></a><span class="co">#&gt; 1          533.0   5.0    33.0</span></span>
<span id="cb86-10"><a href="transform.html#cb86-10"></a><span class="co">#&gt; 2          542.0   5.0    42.0</span></span>
<span id="cb86-11"><a href="transform.html#cb86-11"></a><span class="co">#&gt; 3          544.0   5.0    44.0</span></span>
<span id="cb86-12"><a href="transform.html#cb86-12"></a><span class="co">#&gt; 4          554.0   5.0    54.0</span></span>
<span id="cb86-13"><a href="transform.html#cb86-13"></a><span class="co">#&gt; ...          ...   ...     ...</span></span>
<span id="cb86-14"><a href="transform.html#cb86-14"></a><span class="co">#&gt; 336771       NaN   NaN     NaN</span></span>
<span id="cb86-15"><a href="transform.html#cb86-15"></a><span class="co">#&gt; 336772       NaN   NaN     NaN</span></span>
<span id="cb86-16"><a href="transform.html#cb86-16"></a><span class="co">#&gt; 336773       NaN   NaN     NaN</span></span>
<span id="cb86-17"><a href="transform.html#cb86-17"></a><span class="co">#&gt; 336774       NaN   NaN     NaN</span></span>
<span id="cb86-18"><a href="transform.html#cb86-18"></a><span class="co">#&gt; 336775       NaN   NaN     NaN</span></span>
<span id="cb86-19"><a href="transform.html#cb86-19"></a><span class="co">#&gt; </span></span>
<span id="cb86-20"><a href="transform.html#cb86-20"></a><span class="co">#&gt; [336776 rows x 3 columns]</span></span></code></pre></div></li>
<li><p>Logs: <code>np.log()</code>, <code>np.log2()</code>, <code>np.log10()</code>. Logarithms are an incredibly useful
transformation for dealing with data that ranges across multiple orders of
magnitude. They also convert multiplicative relationships to additive, a
feature we’ll come back to in modelling.</p>
<p>All else being equal, I recommend using <code>np.log2()</code> because it’s easy to
interpret: a difference of 1 on the log scale corresponds to doubling on
the original scale and a difference of -1 corresponds to halving.</p></li>
<li><p>Offsets: <code>shift(1)</code> and <code>shift(-1)</code> allow you to refer to leading or lagging
values. This allows you to compute running differences (e.g. <code>x - x.shift(1)</code>)
or find when values change (<code>x != x.shift(1)</code>). They are most useful in
conjunction with <code>groupby()</code>, which you’ll learn about shortly.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb87-1"><a href="transform.html#cb87-1"></a>x <span class="op">=</span> pd.Series(np.arange(<span class="dv">1</span>,<span class="dv">10</span>))</span>
<span id="cb87-2"><a href="transform.html#cb87-2"></a>x.shift(<span class="dv">1</span>)</span>
<span id="cb87-3"><a href="transform.html#cb87-3"></a><span class="co">#&gt; 0    NaN</span></span>
<span id="cb87-4"><a href="transform.html#cb87-4"></a><span class="co">#&gt; 1    1.0</span></span>
<span id="cb87-5"><a href="transform.html#cb87-5"></a><span class="co">#&gt; 2    2.0</span></span>
<span id="cb87-6"><a href="transform.html#cb87-6"></a><span class="co">#&gt; 3    3.0</span></span>
<span id="cb87-7"><a href="transform.html#cb87-7"></a><span class="co">#&gt; 4    4.0</span></span>
<span id="cb87-8"><a href="transform.html#cb87-8"></a><span class="co">#&gt; 5    5.0</span></span>
<span id="cb87-9"><a href="transform.html#cb87-9"></a><span class="co">#&gt; 6    6.0</span></span>
<span id="cb87-10"><a href="transform.html#cb87-10"></a><span class="co">#&gt; 7    7.0</span></span>
<span id="cb87-11"><a href="transform.html#cb87-11"></a><span class="co">#&gt; 8    8.0</span></span>
<span id="cb87-12"><a href="transform.html#cb87-12"></a><span class="co">#&gt; dtype: float64</span></span>
<span id="cb87-13"><a href="transform.html#cb87-13"></a>x.shift(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb87-14"><a href="transform.html#cb87-14"></a><span class="co">#&gt; 0    2.0</span></span>
<span id="cb87-15"><a href="transform.html#cb87-15"></a><span class="co">#&gt; 1    3.0</span></span>
<span id="cb87-16"><a href="transform.html#cb87-16"></a><span class="co">#&gt; 2    4.0</span></span>
<span id="cb87-17"><a href="transform.html#cb87-17"></a><span class="co">#&gt; 3    5.0</span></span>
<span id="cb87-18"><a href="transform.html#cb87-18"></a><span class="co">#&gt; 4    6.0</span></span>
<span id="cb87-19"><a href="transform.html#cb87-19"></a><span class="co">#&gt; 5    7.0</span></span>
<span id="cb87-20"><a href="transform.html#cb87-20"></a><span class="co">#&gt; 6    8.0</span></span>
<span id="cb87-21"><a href="transform.html#cb87-21"></a><span class="co">#&gt; 7    9.0</span></span>
<span id="cb87-22"><a href="transform.html#cb87-22"></a><span class="co">#&gt; 8    NaN</span></span>
<span id="cb87-23"><a href="transform.html#cb87-23"></a><span class="co">#&gt; dtype: float64</span></span></code></pre></div></li>
<li><p>Cumulative and rolling aggregates: pandas provides functions for running sums,
products, mins and maxes: <code>cumsum()</code>, <code>cumprod()</code>, <code>cummin()</code>, <code>cummax()</code>.
If you need rolling aggregates (i.e. a sum computed over a rolling window),
try the <code>rolling()</code> in the pandas package.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb88-1"><a href="transform.html#cb88-1"></a>x</span>
<span id="cb88-2"><a href="transform.html#cb88-2"></a><span class="co">#&gt; 0    1</span></span>
<span id="cb88-3"><a href="transform.html#cb88-3"></a><span class="co">#&gt; 1    2</span></span>
<span id="cb88-4"><a href="transform.html#cb88-4"></a><span class="co">#&gt; 2    3</span></span>
<span id="cb88-5"><a href="transform.html#cb88-5"></a><span class="co">#&gt; 3    4</span></span>
<span id="cb88-6"><a href="transform.html#cb88-6"></a><span class="co">#&gt; 4    5</span></span>
<span id="cb88-7"><a href="transform.html#cb88-7"></a><span class="co">#&gt; 5    6</span></span>
<span id="cb88-8"><a href="transform.html#cb88-8"></a><span class="co">#&gt; 6    7</span></span>
<span id="cb88-9"><a href="transform.html#cb88-9"></a><span class="co">#&gt; 7    8</span></span>
<span id="cb88-10"><a href="transform.html#cb88-10"></a><span class="co">#&gt; 8    9</span></span>
<span id="cb88-11"><a href="transform.html#cb88-11"></a><span class="co">#&gt; dtype: int64</span></span>
<span id="cb88-12"><a href="transform.html#cb88-12"></a>x.cumsum()</span>
<span id="cb88-13"><a href="transform.html#cb88-13"></a><span class="co">#&gt; 0     1</span></span>
<span id="cb88-14"><a href="transform.html#cb88-14"></a><span class="co">#&gt; 1     3</span></span>
<span id="cb88-15"><a href="transform.html#cb88-15"></a><span class="co">#&gt; 2     6</span></span>
<span id="cb88-16"><a href="transform.html#cb88-16"></a><span class="co">#&gt; 3    10</span></span>
<span id="cb88-17"><a href="transform.html#cb88-17"></a><span class="co">#&gt; 4    15</span></span>
<span id="cb88-18"><a href="transform.html#cb88-18"></a><span class="co">#&gt; 5    21</span></span>
<span id="cb88-19"><a href="transform.html#cb88-19"></a><span class="co">#&gt; 6    28</span></span>
<span id="cb88-20"><a href="transform.html#cb88-20"></a><span class="co">#&gt; 7    36</span></span>
<span id="cb88-21"><a href="transform.html#cb88-21"></a><span class="co">#&gt; 8    45</span></span>
<span id="cb88-22"><a href="transform.html#cb88-22"></a><span class="co">#&gt; dtype: int64</span></span>
<span id="cb88-23"><a href="transform.html#cb88-23"></a>x.rolling(<span class="dv">2</span>).mean()</span>
<span id="cb88-24"><a href="transform.html#cb88-24"></a><span class="co">#&gt; 0    NaN</span></span>
<span id="cb88-25"><a href="transform.html#cb88-25"></a><span class="co">#&gt; 1    1.5</span></span>
<span id="cb88-26"><a href="transform.html#cb88-26"></a><span class="co">#&gt; 2    2.5</span></span>
<span id="cb88-27"><a href="transform.html#cb88-27"></a><span class="co">#&gt; 3    3.5</span></span>
<span id="cb88-28"><a href="transform.html#cb88-28"></a><span class="co">#&gt; 4    4.5</span></span>
<span id="cb88-29"><a href="transform.html#cb88-29"></a><span class="co">#&gt; 5    5.5</span></span>
<span id="cb88-30"><a href="transform.html#cb88-30"></a><span class="co">#&gt; 6    6.5</span></span>
<span id="cb88-31"><a href="transform.html#cb88-31"></a><span class="co">#&gt; 7    7.5</span></span>
<span id="cb88-32"><a href="transform.html#cb88-32"></a><span class="co">#&gt; 8    8.5</span></span>
<span id="cb88-33"><a href="transform.html#cb88-33"></a><span class="co">#&gt; dtype: float64</span></span></code></pre></div></li>
<li><p>Logical comparisons, <code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code>, <code>&gt;=</code>, <code>!=</code>, and <code>==</code>, which you learned about
earlier. If you’re doing a complex sequence of logical operations it’s
often a good idea to store the interim values in new variables so you can
check that each step is working as expected.</p></li>
<li><p>Ranking: there are a number of ranking functions, but you should
start with <code>min_rank()</code>. It does the most usual type of ranking
(e.g. 1st, 2nd, 2nd, 4th). The default gives smallest values the small
ranks; use <code>desc(x)</code> to give the largest values the smallest ranks.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb89-1"><a href="transform.html#cb89-1"></a>y <span class="op">=</span> pd.Series([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, np.nan, <span class="dv">3</span>, <span class="dv">4</span>])</span>
<span id="cb89-2"><a href="transform.html#cb89-2"></a>y.rank(method <span class="op">=</span> <span class="st">&#39;min&#39;</span>)</span>
<span id="cb89-3"><a href="transform.html#cb89-3"></a><span class="co">#&gt; 0    1.0</span></span>
<span id="cb89-4"><a href="transform.html#cb89-4"></a><span class="co">#&gt; 1    2.0</span></span>
<span id="cb89-5"><a href="transform.html#cb89-5"></a><span class="co">#&gt; 2    2.0</span></span>
<span id="cb89-6"><a href="transform.html#cb89-6"></a><span class="co">#&gt; 3    NaN</span></span>
<span id="cb89-7"><a href="transform.html#cb89-7"></a><span class="co">#&gt; 4    4.0</span></span>
<span id="cb89-8"><a href="transform.html#cb89-8"></a><span class="co">#&gt; 5    5.0</span></span>
<span id="cb89-9"><a href="transform.html#cb89-9"></a><span class="co">#&gt; dtype: float64</span></span>
<span id="cb89-10"><a href="transform.html#cb89-10"></a>y.rank(ascending<span class="op">=</span><span class="va">False</span>, method <span class="op">=</span> <span class="st">&#39;min&#39;</span>)</span>
<span id="cb89-11"><a href="transform.html#cb89-11"></a><span class="co">#&gt; 0    5.0</span></span>
<span id="cb89-12"><a href="transform.html#cb89-12"></a><span class="co">#&gt; 1    3.0</span></span>
<span id="cb89-13"><a href="transform.html#cb89-13"></a><span class="co">#&gt; 2    3.0</span></span>
<span id="cb89-14"><a href="transform.html#cb89-14"></a><span class="co">#&gt; 3    NaN</span></span>
<span id="cb89-15"><a href="transform.html#cb89-15"></a><span class="co">#&gt; 4    2.0</span></span>
<span id="cb89-16"><a href="transform.html#cb89-16"></a><span class="co">#&gt; 5    1.0</span></span>
<span id="cb89-17"><a href="transform.html#cb89-17"></a><span class="co">#&gt; dtype: float64</span></span></code></pre></div>
<p>If <code>method = 'min'`` doesn't do what you need, look at the variants</code>method = ‘first’<code>,</code>method = ‘dense’<code>,</code>method = ‘percent’<code>,</code>pct = True`.
See the rank <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rank.html">help page</a> for more details.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb90-1"><a href="transform.html#cb90-1"></a>y.rank(method <span class="op">=</span> <span class="st">&#39;first&#39;</span>)</span>
<span id="cb90-2"><a href="transform.html#cb90-2"></a><span class="co">#&gt; 0    1.0</span></span>
<span id="cb90-3"><a href="transform.html#cb90-3"></a><span class="co">#&gt; 1    2.0</span></span>
<span id="cb90-4"><a href="transform.html#cb90-4"></a><span class="co">#&gt; 2    3.0</span></span>
<span id="cb90-5"><a href="transform.html#cb90-5"></a><span class="co">#&gt; 3    NaN</span></span>
<span id="cb90-6"><a href="transform.html#cb90-6"></a><span class="co">#&gt; 4    4.0</span></span>
<span id="cb90-7"><a href="transform.html#cb90-7"></a><span class="co">#&gt; 5    5.0</span></span>
<span id="cb90-8"><a href="transform.html#cb90-8"></a><span class="co">#&gt; dtype: float64</span></span>
<span id="cb90-9"><a href="transform.html#cb90-9"></a>y.rank(method <span class="op">=</span> <span class="st">&#39;dense&#39;</span>)</span>
<span id="cb90-10"><a href="transform.html#cb90-10"></a><span class="co">#&gt; 0    1.0</span></span>
<span id="cb90-11"><a href="transform.html#cb90-11"></a><span class="co">#&gt; 1    2.0</span></span>
<span id="cb90-12"><a href="transform.html#cb90-12"></a><span class="co">#&gt; 2    2.0</span></span>
<span id="cb90-13"><a href="transform.html#cb90-13"></a><span class="co">#&gt; 3    NaN</span></span>
<span id="cb90-14"><a href="transform.html#cb90-14"></a><span class="co">#&gt; 4    3.0</span></span>
<span id="cb90-15"><a href="transform.html#cb90-15"></a><span class="co">#&gt; 5    4.0</span></span>
<span id="cb90-16"><a href="transform.html#cb90-16"></a><span class="co">#&gt; dtype: float64</span></span>
<span id="cb90-17"><a href="transform.html#cb90-17"></a>y.rank(pct <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb90-18"><a href="transform.html#cb90-18"></a><span class="co">#&gt; 0    0.2</span></span>
<span id="cb90-19"><a href="transform.html#cb90-19"></a><span class="co">#&gt; 1    0.5</span></span>
<span id="cb90-20"><a href="transform.html#cb90-20"></a><span class="co">#&gt; 2    0.5</span></span>
<span id="cb90-21"><a href="transform.html#cb90-21"></a><span class="co">#&gt; 3    NaN</span></span>
<span id="cb90-22"><a href="transform.html#cb90-22"></a><span class="co">#&gt; 4    0.8</span></span>
<span id="cb90-23"><a href="transform.html#cb90-23"></a><span class="co">#&gt; 5    1.0</span></span>
<span id="cb90-24"><a href="transform.html#cb90-24"></a><span class="co">#&gt; dtype: float64</span></span></code></pre></div></li>
</ul>
</div>
<div id="exercises-8" class="section level3" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Currently <code>dep_time</code> and <code>sched_dep_time</code> are convenient to look at, but
hard to compute with because they’re not really continuous numbers.
Convert them to a more convenient representation of number of minutes
since midnight.</p></li>
<li><p>Compare <code>air_time</code> with <code>arr_time - dep_time</code>. What do you expect to see?
What do you see? What do you need to do to fix it?</p></li>
<li><p>Compare <code>dep_time</code>, <code>sched_dep_time</code>, and <code>dep_delay</code>. How would you
expect those three numbers to be related?</p></li>
<li><p>Find the 10 most delayed flights using a ranking function. How do you want
to handle ties? Carefully read the documentation for <code>method = 'min'</code>.</p></li>
<li><p>What trigonometric functions does <strong>NumPy</strong> provide?</p></li>
</ol>
</div>
</div>
<div id="grouped-summaries-or-aggregations-with-agg" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Grouped summaries or aggregations with <code>agg()</code></h2>
<p>The last key verb is <code>agg()</code>. It collapses a data frame to a single row:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb91-1"><a href="transform.html#cb91-1"></a>flights.agg({<span class="st">&#39;dep_delay&#39;</span>: np.mean})</span>
<span id="cb91-2"><a href="transform.html#cb91-2"></a><span class="co">#&gt; dep_delay    12.63907</span></span>
<span id="cb91-3"><a href="transform.html#cb91-3"></a><span class="co">#&gt; dtype: float64</span></span></code></pre></div>
<p>(Pandas aggregate functions ignores the <code>np.nan</code> values like <code>na.rm = TRUE</code> in R.)</p>
<p><code>agg()</code> is not terribly useful unless we pair it with <code>groupby()</code>. This changes the unit of analysis from the complete dataset to individual groups. Then, when you use the pandas functions on a grouped data frame they’ll be automatically applied “by group”. For example, if we applied similiar code to a data frame grouped by date, we get the average delay per date. Note that with the <code>groupby()</code> function we used tuple to identify the column (first entry) and the function to apply on the column (second entry). This is called <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#named-aggregation">named aggregation</a> in pandas:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb92-1"><a href="transform.html#cb92-1"></a>by_day <span class="op">=</span> flights.groupby([<span class="st">&#39;year&#39;</span>, <span class="st">&#39;month&#39;</span>, <span class="st">&#39;day&#39;</span>])</span>
<span id="cb92-2"><a href="transform.html#cb92-2"></a>by_day.agg(delay <span class="op">=</span> (<span class="st">&#39;dep_delay&#39;</span>, np.mean)).reset_index()</span>
<span id="cb92-3"><a href="transform.html#cb92-3"></a><span class="co">#&gt;      year  month  day      delay</span></span>
<span id="cb92-4"><a href="transform.html#cb92-4"></a><span class="co">#&gt; 0    2013      1    1  11.548926</span></span>
<span id="cb92-5"><a href="transform.html#cb92-5"></a><span class="co">#&gt; 1    2013      1    2  13.858824</span></span>
<span id="cb92-6"><a href="transform.html#cb92-6"></a><span class="co">#&gt; 2    2013      1    3  10.987832</span></span>
<span id="cb92-7"><a href="transform.html#cb92-7"></a><span class="co">#&gt; 3    2013      1    4   8.951595</span></span>
<span id="cb92-8"><a href="transform.html#cb92-8"></a><span class="co">#&gt; 4    2013      1    5   5.732218</span></span>
<span id="cb92-9"><a href="transform.html#cb92-9"></a><span class="co">#&gt; ..    ...    ...  ...        ...</span></span>
<span id="cb92-10"><a href="transform.html#cb92-10"></a><span class="co">#&gt; 360  2013     12   27  10.937630</span></span>
<span id="cb92-11"><a href="transform.html#cb92-11"></a><span class="co">#&gt; 361  2013     12   28   7.981550</span></span>
<span id="cb92-12"><a href="transform.html#cb92-12"></a><span class="co">#&gt; 362  2013     12   29  22.309551</span></span>
<span id="cb92-13"><a href="transform.html#cb92-13"></a><span class="co">#&gt; 363  2013     12   30  10.698113</span></span>
<span id="cb92-14"><a href="transform.html#cb92-14"></a><span class="co">#&gt; 364  2013     12   31   6.996053</span></span>
<span id="cb92-15"><a href="transform.html#cb92-15"></a><span class="co">#&gt; </span></span>
<span id="cb92-16"><a href="transform.html#cb92-16"></a><span class="co">#&gt; [365 rows x 4 columns]</span></span></code></pre></div>
<p>Note the use of <code>reset_index()</code> to remove pandas creation of a <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced-hierarchical">MultiIndex</a>. You can read more about the use of grouby in pandas with their <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html">Group By: split-apply-combine user Guid documentation</a></p>
<p>Together <code>groupby()</code> and <code>agg()</code> provide one of the tools that you’ll use most commonly when working with pandas: grouped summaries. But before we go any further with this, we need to introduce a structure for pandas code when doing data science work. We structure our code much like ‘the pipe’, <code>%&gt;%</code> in the tidyverse packages from R-Studio.</p>
<div id="combining-multiple-operations-with-the-pipe" class="section level3" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Combining multiple operations with the pipe</h3>
<p>Imagine that we want to explore the relationship between the distance and average delay for each location. Using what you know about pandas, you might write code like this:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb93-1"><a href="transform.html#cb93-1"></a>by_dest <span class="op">=</span> flights.groupby(<span class="st">&#39;dest&#39;</span>)</span>
<span id="cb93-2"><a href="transform.html#cb93-2"></a>delay <span class="op">=</span> by_dest.agg(</span>
<span id="cb93-3"><a href="transform.html#cb93-3"></a>    count <span class="op">=</span> (<span class="st">&#39;distance&#39;</span>, <span class="st">&#39;size&#39;</span>),</span>
<span id="cb93-4"><a href="transform.html#cb93-4"></a>  dist <span class="op">=</span> (<span class="st">&#39;distance&#39;</span>, np.mean),</span>
<span id="cb93-5"><a href="transform.html#cb93-5"></a>  delay <span class="op">=</span> (<span class="st">&#39;arr_delay&#39;</span>, np.mean)</span>
<span id="cb93-6"><a href="transform.html#cb93-6"></a>)</span>
<span id="cb93-7"><a href="transform.html#cb93-7"></a>delay <span class="op">=</span> delay.query(<span class="st">&#39;count &gt; 20 &amp; dest != &quot;HNL&quot;&#39;</span>)</span>
<span id="cb93-8"><a href="transform.html#cb93-8"></a></span>
<span id="cb93-9"><a href="transform.html#cb93-9"></a><span class="co"># It looks like delays increase with distance up to ~750 miles</span></span>
<span id="cb93-10"><a href="transform.html#cb93-10"></a><span class="co"># and then decrease. Maybe as flights get longer there&#39;s more</span></span>
<span id="cb93-11"><a href="transform.html#cb93-11"></a><span class="co"># ability to make up delays in the air?</span></span>
<span id="cb93-12"><a href="transform.html#cb93-12"></a>chart_base <span class="op">=</span> (alt.Chart(delay).</span>
<span id="cb93-13"><a href="transform.html#cb93-13"></a>  encode(</span>
<span id="cb93-14"><a href="transform.html#cb93-14"></a>    x <span class="op">=</span> <span class="st">&#39;dist&#39;</span>,</span>
<span id="cb93-15"><a href="transform.html#cb93-15"></a>    y <span class="op">=</span> <span class="st">&#39;delay&#39;</span></span>
<span id="cb93-16"><a href="transform.html#cb93-16"></a>  ))</span>
<span id="cb93-17"><a href="transform.html#cb93-17"></a>  </span>
<span id="cb93-18"><a href="transform.html#cb93-18"></a>chart <span class="op">=</span> chart_base.mark_point() <span class="op">+</span> chart_base.transform_loess(<span class="st">&#39;dist&#39;</span>, <span class="st">&#39;delay&#39;</span>).mark_line()  </span></code></pre></div>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="transform.html#cb94-1"></a>vegawidget<span class="op">::</span><span class="kw">as_vegaspec</span>(py<span class="op">$</span>chart<span class="op">$</span><span class="kw">to_json</span>())</span></code></pre></div>
<div id="htmlwidget-ac96cb3ee4656e2e9ec3" style="width:auto;height:auto;" class="vegawidget html-widget"></div>
<script type="application/json" data-for="htmlwidget-ac96cb3ee4656e2e9ec3">{"x":{
  "chart_spec": {
    "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
    "config": {
      "view": {
        "continuousHeight": 300,
        "continuousWidth": 400
      }
    },
    "data": {
      "name": "data-3702ca1c412d99811a48df476b255e71"
    },
    "datasets": {
      "data-3702ca1c412d99811a48df476b255e71": [
        {
          "count": 254,
          "delay": 4.3819,
          "dist": 1826
        },
        {
          "count": 265,
          "delay": 4.8523,
          "dist": 199
        },
        {
          "count": 439,
          "delay": 14.3971,
          "dist": 143
        },
        {
          "count": 17215,
          "delay": 11.3001,
          "dist": 757.1082
        },
        {
          "count": 2439,
          "delay": 6.0199,
          "dist": 1514.253
        },
        {
          "count": 275,
          "delay": 8.0038,
          "dist": 583.5818
        },
        {
          "count": 443,
          "delay": 7.0485,
          "dist": 116
        },
        {
          "count": 375,
          "delay": 8.0279,
          "dist": 378
        },
        {
          "count": 297,
          "delay": 16.8773,
          "dist": 865.9966
        },
        {
          "count": 6333,
          "delay": 11.8125,
          "dist": 758.2135
        },
        {
          "count": 15508,
          "delay": 2.9144,
          "dist": 190.637
        },
        {
          "count": 896,
          "delay": 8.2455,
          "dist": 1578.9833
        },
        {
          "count": 2589,
          "delay": 8.951,
          "dist": 265.0915
        },
        {
          "count": 4681,
          "delay": 8.946,
          "dist": 296.8084
        },
        {
          "count": 371,
          "delay": 8.1757,
          "dist": 2465
        },
        {
          "count": 1781,
          "delay": 10.7267,
          "dist": 179.4183
        },
        {
          "count": 36,
          "delay": 7.6,
          "dist": 1882
        },
        {
          "count": 116,
          "delay": 41.7642,
          "dist": 603.5517
        },
        {
          "count": 864,
          "delay": 19.6983,
          "dist": 397
        },
        {
          "count": 52,
          "delay": 9.5,
          "dist": 305
        },
        {
          "count": 2884,
          "delay": 10.593,
          "dist": 632.9168
        },
        {
          "count": 4573,
          "delay": 9.1816,
          "dist": 414.1743
        },
        {
          "count": 14064,
          "delay": 7.3603,
          "dist": 538.0273
        },
        {
          "count": 3524,
          "delay": 10.6013,
          "dist": 476.5551
        },
        {
          "count": 138,
          "delay": 14.6716,
          "dist": 444
        },
        {
          "count": 3941,
          "delay": 15.3646,
          "dist": 575.1599
        },
        {
          "count": 1525,
          "delay": 12.6805,
          "dist": 537.1023
        },
        {
          "count": 9705,
          "delay": 9.067,
          "dist": 211.0062
        },
        {
          "count": 7266,
          "delay": 8.6065,
          "dist": 1614.6784
        },
        {
          "count": 8738,
          "delay": 0.3221,
          "dist": 1383.043
        },
        {
          "count": 569,
          "delay": 19.0057,
          "dist": 1020.8875
        },
        {
          "count": 9384,
          "delay": 5.43,
          "dist": 498.1285
        },
        {
          "count": 213,
          "delay": 6.3043,
          "dist": 1735.7089
        },
        {
          "count": 12055,
          "delay": 8.0821,
          "dist": 1070.0688
        },
        {
          "count": 765,
          "delay": 18.1896,
          "dist": 605.7817
        },
        {
          "count": 1606,
          "delay": 14.1126,
          "dist": 449.8418
        },
        {
          "count": 849,
          "delay": 15.9354,
          "dist": 595.96
        },
        {
          "count": 2115,
          "delay": 7.1762,
          "dist": 1420.1551
        },
        {
          "count": 5700,
          "delay": 13.8642,
          "dist": 224.8468
        },
        {
          "count": 7198,
          "delay": 4.2408,
          "dist": 1407.2067
        },
        {
          "count": 110,
          "delay": 4.6355,
          "dist": 500
        },
        {
          "count": 2077,
          "delay": 9.9404,
          "dist": 652.2629
        },
        {
          "count": 25,
          "delay": 28.0952,
          "dist": 1875.6
        },
        {
          "count": 2720,
          "delay": 11.8448,
          "dist": 824.6761
        },
        {
          "count": 5997,
          "delay": 0.2577,
          "dist": 2240.9615
        },
        {
          "count": 16174,
          "delay": 0.5471,
          "dist": 2468.6224
        },
        {
          "count": 668,
          "delay": -0.062,
          "dist": 2465
        },
        {
          "count": 2008,
          "delay": 14.5141,
          "dist": 1097.6952
        },
        {
          "count": 14082,
          "delay": 5.4546,
          "dist": 943.1106
        },
        {
          "count": 4113,
          "delay": 12.3642,
          "dist": 718.046
        },
        {
          "count": 1789,
          "delay": 10.6453,
          "dist": 954.2012
        },
        {
          "count": 1009,
          "delay": 14.7876,
          "dist": 207.0297
        },
        {
          "count": 11728,
          "delay": 0.2991,
          "dist": 1091.5524
        },
        {
          "count": 2802,
          "delay": 14.1672,
          "dist": 733.3815
        },
        {
          "count": 572,
          "delay": 20.196,
          "dist": 803.9545
        },
        {
          "count": 7185,
          "delay": 7.2702,
          "dist": 1017.4017
        },
        {
          "count": 3799,
          "delay": 6.4902,
          "dist": 1177.7057
        },
        {
          "count": 221,
          "delay": -0.2857,
          "dist": 173
        },
        {
          "count": 59,
          "delay": 4.6034,
          "dist": 550.661
        },
        {
          "count": 312,
          "delay": 3.0777,
          "dist": 2576
        },
        {
          "count": 346,
          "delay": 30.619,
          "dist": 1325
        },
        {
          "count": 849,
          "delay": 14.6989,
          "dist": 1135.5665
        },
        {
          "count": 17283,
          "delay": 5.8766,
          "dist": 729.0008
        },
        {
          "count": 1536,
          "delay": 10.9491,
          "dist": 288.5234
        },
        {
          "count": 6554,
          "delay": 8.563,
          "dist": 1028.8381
        },
        {
          "count": 1354,
          "delay": 5.1416,
          "dist": 2445.5657
        },
        {
          "count": 1632,
          "delay": 10.1272,
          "dist": 94.3235
        },
        {
          "count": 4656,
          "delay": 2.097,
          "dist": 2141.3033
        },
        {
          "count": 2875,
          "delay": 7.681,
          "dist": 334.0612
        },
        {
          "count": 365,
          "delay": 7.8715,
          "dist": 1617
        },
        {
          "count": 376,
          "delay": 16.2346,
          "dist": 160
        },
        {
          "count": 2352,
          "delay": 11.6604,
          "dist": 276.1284
        },
        {
          "count": 8163,
          "delay": 10.0524,
          "dist": 426.7577
        },
        {
          "count": 2454,
          "delay": 20.1113,
          "dist": 281.4046
        },
        {
          "count": 2416,
          "delay": 11.5606,
          "dist": 259.2508
        },
        {
          "count": 3537,
          "delay": 3.2381,
          "dist": 1072.8533
        },
        {
          "count": 2737,
          "delay": 3.1392,
          "dist": 2437.2992
        },
        {
          "count": 686,
          "delay": 6.9454,
          "dist": 1578.3411
        },
        {
          "count": 804,
          "delay": 15.1295,
          "dist": 709.1841
        },
        {
          "count": 1157,
          "delay": 12.6694,
          "dist": 645.9836
        },
        {
          "count": 3923,
          "delay": -1.0991,
          "dist": 2412.6653
        },
        {
          "count": 13331,
          "delay": 2.6729,
          "dist": 2577.9236
        },
        {
          "count": 329,
          "delay": 3.4482,
          "dist": 2569
        },
        {
          "count": 5819,
          "delay": 2.5205,
          "dist": 1599.8336
        },
        {
          "count": 2467,
          "delay": 0.1763,
          "dist": 1986.9866
        },
        {
          "count": 284,
          "delay": 12.1099,
          "dist": 2521
        },
        {
          "count": 825,
          "delay": -7.8682,
          "dist": 2434
        },
        {
          "count": 1211,
          "delay": 3.0824,
          "dist": 1044.6515
        },
        {
          "count": 4339,
          "delay": 11.0785,
          "dist": 878.7232
        },
        {
          "count": 522,
          "delay": -3.8359,
          "dist": 1626.9828
        },
        {
          "count": 1761,
          "delay": 8.9039,
          "dist": 205.9216
        },
        {
          "count": 7466,
          "delay": 7.4085,
          "dist": 1003.9356
        },
        {
          "count": 315,
          "delay": 33.6599,
          "dist": 1215
        },
        {
          "count": 101,
          "delay": 12.9684,
          "dist": 652.3861
        },
        {
          "count": 631,
          "delay": 24.0692,
          "dist": 638.8098
        },
        {
          "count": 1036,
          "delay": 7.4657,
          "dist": 1142.5058
        }
      ]
    },
    "layer": [
      {
        "encoding": {
          "x": {
            "field": "dist",
            "type": "quantitative"
          },
          "y": {
            "field": "delay",
            "type": "quantitative"
          }
        },
        "mark": "point"
      },
      {
        "encoding": {
          "x": {
            "field": "dist",
            "type": "quantitative"
          },
          "y": {
            "field": "delay",
            "type": "quantitative"
          }
        },
        "mark": "line",
        "transform": [
          {
            "loess": "delay",
            "on": "dist"
          }
        ]
      }
    ]
  },
  "embed_options": {
    "defaultStyle": true,
    "renderer": "canvas"
  }
},"evals":[],"jsHooks":[]}</script>
<p>There are three steps to prepare this data:</p>
<ol style="list-style-type: decimal">
<li><p>Group flights by destination.</p></li>
<li><p>Summarise to compute distance, average delay, and number of flights.</p></li>
<li><p>Filter to remove noisy points and Honolulu airport, which is almost
twice as far away as the next closest airport.</p></li>
</ol>
<p>This code is a little frustrating to write because we have to give each intermediate data frame a name, even though we don’t care about it. Naming things is hard, so this slows down our analysis.</p>
<p>There’s another way to tackle the same problem without the additional objects:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb95-1"><a href="transform.html#cb95-1"></a>delays <span class="op">=</span> (flights.</span>
<span id="cb95-2"><a href="transform.html#cb95-2"></a>    groupby(<span class="st">&#39;dest&#39;</span>).</span>
<span id="cb95-3"><a href="transform.html#cb95-3"></a>    agg(</span>
<span id="cb95-4"><a href="transform.html#cb95-4"></a>        count <span class="op">=</span> (<span class="st">&#39;distance&#39;</span>, <span class="st">&#39;size&#39;</span>),</span>
<span id="cb95-5"><a href="transform.html#cb95-5"></a>        dist <span class="op">=</span> (<span class="st">&#39;distance&#39;</span>, np.mean),</span>
<span id="cb95-6"><a href="transform.html#cb95-6"></a>        delay <span class="op">=</span> (<span class="st">&#39;arr_delay&#39;</span>, np.mean) </span>
<span id="cb95-7"><a href="transform.html#cb95-7"></a>    ).</span>
<span id="cb95-8"><a href="transform.html#cb95-8"></a>    query(<span class="st">&#39;count &gt; 20 &amp; dest != &quot;HNL&quot;&#39;</span>))</span></code></pre></div>
<p>This focuses on the transformations, not what’s being transformed, which makes the code easier to read. You can read it as a series of imperative statements: group, then summarise, then filter. As suggested by this reading, a good way to pronounce <code>.</code> when reading pandas code is “then”.</p>
<p>You can use the <code>()</code> with <code>.</code> to rewrite multiple operations in a way that you can read left-to-right, top-to-bottom. We’ll use this format frequently from now on because it considerably improves the readability of complex pandas code.</p>
<!-- ### Missing values -->
<!-- You may have wondered about the `na.rm` argument we used above. What happens if we don't set it? -->
<!-- ```{r} -->
<!-- flights %>%  -->
<!--   group_by(year, month, day) %>%  -->
<!--   summarise(mean = mean(dep_delay)) -->
<!-- ``` -->
<!-- We get a lot of missing values! That's because aggregation functions obey the usual rule of missing values: if there's any missing value in the input, the output will be a missing value. Fortunately, all aggregation functions have an `na.rm` argument which removes the missing values prior to computation: -->
<!-- ```{r} -->
<!-- flights %>%  -->
<!--   group_by(year, month, day) %>%  -->
<!--   summarise(mean = mean(dep_delay, na.rm = TRUE)) -->
<!-- ``` -->
<!-- In this case, where missing values represent cancelled flights, we could also tackle the problem by first removing the cancelled flights. We'll save this dataset so we can reuse it in the next few examples. -->
<!-- ```{r} -->
<!-- not_cancelled <- flights %>%  -->
<!--   filter(!is.na(dep_delay), !is.na(arr_delay)) -->
<!-- not_cancelled %>%  -->
<!--   group_by(year, month, day) %>%  -->
<!--   summarise(mean = mean(dep_delay)) -->
<!-- ``` -->
<!-- ### Counts -->
<!-- Whenever you do any aggregation, it's always a good idea to include either a count (`n()`), or a count of non-missing values (`sum(!is.na(x))`). That way you can check that you're not drawing conclusions based on very small amounts of data. For example, let's look at the planes (identified by their tail number) that have the highest average delays: -->
<!-- ```{r} -->
<!-- delays <- not_cancelled %>%  -->
<!--   group_by(tailnum) %>%  -->
<!--   summarise( -->
<!--     delay = mean(arr_delay) -->
<!--   ) -->
<!-- ggplot(data = delays, mapping = aes(x = delay)) +  -->
<!--   geom_freqpoly(binwidth = 10) -->
<!-- ``` -->
<!-- Wow, there are some planes that have an _average_ delay of 5 hours (300 minutes)! -->
<!-- The story is actually a little more nuanced. We can get more insight if we draw a scatterplot of number of flights vs. average delay: -->
<!-- ```{r} -->
<!-- delays <- not_cancelled %>%  -->
<!--   group_by(tailnum) %>%  -->
<!--   summarise( -->
<!--     delay = mean(arr_delay, na.rm = TRUE), -->
<!--     n = n() -->
<!--   ) -->
<!-- ggplot(data = delays, mapping = aes(x = n, y = delay)) +  -->
<!--   geom_point(alpha = 1/10) -->
<!-- ``` -->
<!-- Not surprisingly, there is much greater variation in the average delay when there are few flights. The shape of this plot is very characteristic: whenever you plot a mean (or other summary) vs. group size, you'll see that the variation decreases as the sample size increases. -->
<!-- When looking at this sort of plot, it's often useful to filter out the groups with the smallest numbers of observations, so you can see more of the pattern and less of the extreme variation in the smallest groups. This is what the following code does, as well as showing you a handy pattern for integrating ggplot2 into dplyr flows. It's a bit painful that you have to switch from `%>%` to `+`, but once you get the hang of it, it's quite convenient. -->
<!-- ```{r} -->
<!-- delays %>%  -->
<!--   filter(n > 25) %>%  -->
<!--   ggplot(mapping = aes(x = n, y = delay)) +  -->
<!--     geom_point(alpha = 1/10) -->
<!-- ``` -->
<!-- -------------------------------------------------------------------------------- -->
<!-- RStudio tip: a useful keyboard shortcut is Cmd/Ctrl + Shift + P. This resends the previously sent chunk from the editor to the console. This is very convenient when you're (e.g.) exploring the value of `n` in the example above. You send the whole block once with Cmd/Ctrl + Enter, then you modify the value of `n` and press Cmd/Ctrl + Shift + P to resend the complete block. -->
<!-- -------------------------------------------------------------------------------- -->
<!-- There's another common variation of this type of pattern. Let's look at how the average performance of batters in baseball is related to the number of times they're at bat. Here I use data from the __Lahman__ package to compute the batting average (number of hits / number of attempts) of every major league baseball player.   -->
<!-- When I plot the skill of the batter (measured by the batting average, `ba`) against the number of opportunities to hit the ball (measured by at bat, `ab`), you see two patterns: -->
<!-- 1.  As above, the variation in our aggregate decreases as we get more  -->
<!--     data points. -->
<!-- 2.  There's a positive correlation between skill (`ba`) and opportunities to  -->
<!--     hit the ball (`ab`). This is because teams control who gets to play,  -->
<!--     and obviously they'll pick their best players. -->
<!-- ```{r} -->
<!-- # Convert to a tibble so it prints nicely -->
<!-- batting <- as_tibble(Lahman::Batting) -->
<!-- batters <- batting %>%  -->
<!--   group_by(playerID) %>%  -->
<!--   summarise( -->
<!--     ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE), -->
<!--     ab = sum(AB, na.rm = TRUE) -->
<!--   ) -->
<!-- batters %>%  -->
<!--   filter(ab > 100) %>%  -->
<!--   ggplot(mapping = aes(x = ab, y = ba)) + -->
<!--     geom_point() +  -->
<!--     geom_smooth(se = FALSE) -->
<!-- ``` -->
<!-- This also has important implications for ranking. If you naively sort on `desc(ba)`, the people with the best batting averages are clearly lucky, not skilled: -->
<!-- ```{r} -->
<!-- batters %>%  -->
<!--   arrange(desc(ba)) -->
<!-- ``` -->
<!-- You can find a good explanation of this problem at <http://varianceexplained.org/r/empirical_bayes_baseball/> and <http://www.evanmiller.org/how-not-to-sort-by-average-rating.html>. -->
<!-- ### Useful summary functions {#summarise-funs} -->
<!-- Just using means, counts, and sum can get you a long way, but R provides many other useful summary functions: -->
<!-- *   Measures of location: we've used `mean(x)`, but `median(x)` is also -->
<!--     useful. The mean is the sum divided by the length; the median is a value  -->
<!--     where 50% of `x` is above it, and 50% is below it. -->
<!--     It's sometimes useful to combine aggregation with logical subsetting.  -->
<!--     We haven't talked about this sort of subsetting yet, but you'll learn more -->
<!--     about it in [subsetting]. -->
<!--     ```{r} -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       summarise( -->
<!--         avg_delay1 = mean(arr_delay), -->
<!--         avg_delay2 = mean(arr_delay[arr_delay > 0]) # the average positive delay -->
<!--       ) -->
<!--     ``` -->
<!-- *   Measures of spread: `sd(x)`, `IQR(x)`, `mad(x)`. The root mean squared deviation, -->
<!--     or standard deviation `sd(x)`, is the standard measure of spread. -->
<!--     The interquartile range `IQR(x)` and median absolute deviation `mad(x)` -->
<!--     are robust equivalents that may be more useful if you have outliers. -->
<!--     ```{r} -->
<!--     # Why is distance to some destinations more variable than to others? -->
<!--     not_cancelled %>%  -->
<!--       group_by(dest) %>%  -->
<!--       summarise(distance_sd = sd(distance)) %>%  -->
<!--       arrange(desc(distance_sd)) -->
<!--     ``` -->
<!-- *   Measures of rank: `min(x)`, `quantile(x, 0.25)`, `max(x)`. Quantiles -->
<!--     are a generalisation of the median. For example, `quantile(x, 0.25)` -->
<!--     will find a value of `x` that is greater than 25% of the values, -->
<!--     and less than the remaining 75%. -->
<!--     ```{r} -->
<!--     # When do the first and last flights leave each day? -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       summarise( -->
<!--         first = min(dep_time), -->
<!--         last = max(dep_time) -->
<!--       ) -->
<!--     ``` -->
<!-- *   Measures of position: `first(x)`, `nth(x, 2)`, `last(x)`. These work  -->
<!--     similarly to `x[1]`, `x[2]`, and `x[length(x)]` but let you set a default  -->
<!--     value if that position does not exist (i.e. you're trying to get the 3rd -->
<!--     element from a group that only has two elements). For example, we can -->
<!--     find the first and last departure for each day: -->
<!--     ```{r} -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       summarise( -->
<!--         first_dep = first(dep_time),  -->
<!--         last_dep = last(dep_time) -->
<!--       ) -->
<!--     ``` -->
<!--     These functions are complementary to filtering on ranks. Filtering gives -->
<!--     you all variables, with each observation in a separate row: -->
<!--     ```{r} -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       mutate(r = min_rank(desc(dep_time))) %>%  -->
<!--       filter(r %in% range(r)) -->
<!--     ``` -->
<!-- *   Counts: You've seen `n()`, which takes no arguments, and returns the  -->
<!--     size of the current group. To count the number of non-missing values, use -->
<!--     `sum(!is.na(x))`. To count the number of distinct (unique) values, use -->
<!--     `n_distinct(x)`. -->
<!--     ```{r} -->
<!--     # Which destinations have the most carriers? -->
<!--     not_cancelled %>%  -->
<!--       group_by(dest) %>%  -->
<!--       summarise(carriers = n_distinct(carrier)) %>%  -->
<!--       arrange(desc(carriers)) -->
<!--     ``` -->
<!--     Counts are so useful that dplyr provides a simple helper if all you want is  -->
<!--     a count: -->
<!--     ```{r} -->
<!--     not_cancelled %>%  -->
<!--       count(dest) -->
<!--     ``` -->
<!--     You can optionally provide a weight variable. For example, you could use  -->
<!--     this to "count" (sum) the total number of miles a plane flew: -->
<!--     ```{r} -->
<!--     not_cancelled %>%  -->
<!--       count(tailnum, wt = distance) -->
<!--     ``` -->
<!-- *   Counts and proportions of logical values: `sum(x > 10)`, `mean(y == 0)`. -->
<!--     When used with numeric functions, `TRUE` is converted to 1 and `FALSE` to 0.  -->
<!--     This makes `sum()` and `mean()` very useful: `sum(x)` gives the number of  -->
<!--     `TRUE`s in `x`, and `mean(x)` gives the proportion. -->
<!--     ```{r} -->
<!--     # How many flights left before 5am? (these usually indicate delayed -->
<!--     # flights from the previous day) -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       summarise(n_early = sum(dep_time < 500)) -->
<!--     # What proportion of flights are delayed by more than an hour? -->
<!--     not_cancelled %>%  -->
<!--       group_by(year, month, day) %>%  -->
<!--       summarise(hour_prop = mean(arr_delay > 60)) -->
<!--     ``` -->
<!-- ### Grouping by multiple variables -->
<!-- When you group by multiple variables, each summary peels off one level of the grouping. That makes it easy to progressively roll up a dataset: -->
<!-- ```{r} -->
<!-- daily <- group_by(flights, year, month, day) -->
<!-- (per_day   <- summarise(daily, flights = n())) -->
<!-- (per_month <- summarise(per_day, flights = sum(flights))) -->
<!-- (per_year  <- summarise(per_month, flights = sum(flights))) -->
<!-- ``` -->
<!-- Be careful when progressively rolling up summaries: it's OK for sums and counts, but you need to think about weighting means and variances, and it's not possible to do it exactly for rank-based statistics like the median. In other words, the sum of groupwise sums is the overall sum, but the median of groupwise medians is not the overall median. -->
<!-- ### Ungrouping -->
<!-- If you need to remove grouping, and return to operations on ungrouped data, use `ungroup()`.  -->
<!-- ```{r} -->
<!-- daily %>%  -->
<!--   ungroup() %>%             # no longer grouped by date -->
<!--   summarise(flights = n())  # all flights -->
<!-- ``` -->
<!-- ### Exercises -->
<!-- 1.  Brainstorm at least 5 different ways to assess the typical delay  -->
<!--     characteristics of a group of flights. Consider the following scenarios: -->
<!--     * A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of  -->
<!--       the time. -->
<!--     * A flight is always 10 minutes late. -->
<!--     * A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of  -->
<!--       the time. -->
<!--     * 99% of the time a flight is on time. 1% of the time it's 2 hours late. -->
<!--     Which is more important: arrival delay or departure delay? -->
<!-- 1.  Come up with another approach that will give you the same output as  -->
<!--     `not_cancelled %>% count(dest)` and  -->
<!--     `not_cancelled %>% count(tailnum, wt = distance)` (without using  -->
<!--     `count()`). -->
<!-- 1.  Our definition of cancelled flights (`is.na(dep_delay) | is.na(arr_delay)` -->
<!--     ) is slightly suboptimal. Why? Which is the most important column? -->
<!-- 1.  Look at the number of cancelled flights per day. Is there a pattern? -->
<!--     Is the proportion of cancelled flights related to the average delay? -->
<!-- 1.  Which carrier has the worst delays? Challenge: can you disentangle the -->
<!--     effects of bad airports vs. bad carriers? Why/why not? (Hint: think about -->
<!--     `flights %>% group_by(carrier, dest) %>% summarise(n())`) -->
<!-- 1.  What does the `sort` argument to `count()` do. When might you use it? -->
<!-- ## Grouped mutates (and filters) -->
<!-- Grouping is most useful in conjunction with `summarise()`, but you can also do convenient operations with `mutate()` and `filter()`: -->
<!-- *   Find the worst members of each group: -->
<!--     ```{r} -->
<!--     flights_sml %>%  -->
<!--       group_by(year, month, day) %>% -->
<!--       filter(rank(desc(arr_delay)) < 10) -->
<!--     ``` -->
<!-- *   Find all groups bigger than a threshold: -->
<!--     ```{r} -->
<!--     popular_dests <- flights %>%  -->
<!--       group_by(dest) %>%  -->
<!--       filter(n() > 365) -->
<!--     popular_dests -->
<!--     ``` -->
<!-- *   Standardise to compute per group metrics: -->
<!--     ```{r} -->
<!--     popular_dests %>%  -->
<!--       filter(arr_delay > 0) %>%  -->
<!--       mutate(prop_delay = arr_delay / sum(arr_delay)) %>%  -->
<!--       select(year:day, dest, arr_delay, prop_delay) -->
<!--     ``` -->
<!-- A grouped filter is a grouped mutate followed by an ungrouped filter. I generally avoid them except for quick and dirty manipulations: otherwise it's hard to check that you've done the manipulation correctly. -->
<!-- Functions that work most naturally in grouped mutates and filters are known as  window functions (vs. the summary functions used for summaries). You can learn more about useful window functions in the corresponding vignette: `vignette("window-functions")`. -->
<!-- ### Exercises -->
<!-- 1.  Refer back to the lists of useful mutate and filtering functions.  -->
<!--     Describe how each operation changes when you combine it with grouping. -->
<!-- 1.  Which plane (`tailnum`) has the worst on-time record? -->
<!-- 1.  What time of day should you fly if you want to avoid delays as much -->
<!--     as possible? -->
<!-- 1.  For each destination, compute the total minutes of delay. For each  -->
<!--     flight, compute the proportion of the total delay for its destination. -->
<!-- 1.  Delays are typically temporally correlated: even once the problem that -->
<!--     caused the initial delay has been resolved, later flights are delayed  -->
<!--     to allow earlier flights to leave. Using `lag()`, explore how the delay -->
<!--     of a flight is related to the delay of the immediately preceding flight. -->
<!-- 1.  Look at each destination. Can you find flights that are suspiciously -->
<!--     fast? (i.e. flights that represent a potential data entry error). Compute -->
<!--     the air time of a flight relative to the shortest flight to that destination. -->
<!--     Which flights were most delayed in the air? -->
<!-- 1.  Find all destinations that are flown by at least two carriers. Use that -->
<!--     information to rank the carriers. -->
<!-- 1.  For each plane, count the number of flights before the first delay  -->
<!--     of greater than 1 hour. -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="workflow-basics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="workflow-scripts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/byuidatascience/python4ds/edit/master/transform.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
